#!/bin/bash/

python simulate_FG_BG_only.py 600 eRASS8
python simulate_FG_BG_only.py 601 eRASS8
python simulate_FG_BG_only.py 602 eRASS8
python simulate_FG_BG_only.py 603 eRASS8
python simulate_FG_BG_only.py 604 eRASS8
python simulate_FG_BG_only.py 605 eRASS8
python simulate_FG_BG_only.py 606 eRASS8
python simulate_FG_BG_only.py 607 eRASS8
python simulate_FG_BG_only.py 608 eRASS8
python simulate_FG_BG_only.py 609 eRASS8
python simulate_FG_BG_only.py 610 eRASS8
python simulate_FG_BG_only.py 611 eRASS8
python simulate_FG_BG_only.py 612 eRASS8
python simulate_FG_BG_only.py 613 eRASS8
python simulate_FG_BG_only.py 614 eRASS8
python simulate_FG_BG_only.py 615 eRASS8
python simulate_FG_BG_only.py 616 eRASS8
python simulate_FG_BG_only.py 617 eRASS8
python simulate_FG_BG_only.py 618 eRASS8
python simulate_FG_BG_only.py 619 eRASS8
python simulate_FG_BG_only.py 620 eRASS8
python simulate_FG_BG_only.py 621 eRASS8
python simulate_FG_BG_only.py 622 eRASS8
python simulate_FG_BG_only.py 623 eRASS8
python simulate_FG_BG_only.py 624 eRASS8
python simulate_FG_BG_only.py 625 eRASS8
python simulate_FG_BG_only.py 626 eRASS8
python simulate_FG_BG_only.py 627 eRASS8
python simulate_FG_BG_only.py 628 eRASS8
python simulate_FG_BG_only.py 629 eRASS8
python simulate_FG_BG_only.py 630 eRASS8
python simulate_FG_BG_only.py 631 eRASS8
python simulate_FG_BG_only.py 632 eRASS8
python simulate_FG_BG_only.py 633 eRASS8
python simulate_FG_BG_only.py 634 eRASS8
python simulate_FG_BG_only.py 635 eRASS8
python simulate_FG_BG_only.py 636 eRASS8
python simulate_FG_BG_only.py 637 eRASS8
python simulate_FG_BG_only.py 638 eRASS8
python simulate_FG_BG_only.py 639 eRASS8
python simulate_FG_BG_only.py 640 eRASS8
python simulate_FG_BG_only.py 641 eRASS8
python simulate_FG_BG_only.py 642 eRASS8
python simulate_FG_BG_only.py 643 eRASS8
python simulate_FG_BG_only.py 644 eRASS8
python simulate_FG_BG_only.py 645 eRASS8
python simulate_FG_BG_only.py 646 eRASS8
python simulate_FG_BG_only.py 647 eRASS8
python simulate_FG_BG_only.py 648 eRASS8
python simulate_FG_BG_only.py 649 eRASS8
python simulate_FG_BG_only.py 650 eRASS8
python simulate_FG_BG_only.py 651 eRASS8
python simulate_FG_BG_only.py 652 eRASS8
python simulate_FG_BG_only.py 653 eRASS8
python simulate_FG_BG_only.py 654 eRASS8
python simulate_FG_BG_only.py 655 eRASS8
python simulate_FG_BG_only.py 656 eRASS8
python simulate_FG_BG_only.py 657 eRASS8
python simulate_FG_BG_only.py 658 eRASS8
python simulate_FG_BG_only.py 659 eRASS8
python simulate_FG_BG_only.py 660 eRASS8
python simulate_FG_BG_only.py 661 eRASS8
python simulate_FG_BG_only.py 662 eRASS8
python simulate_FG_BG_only.py 663 eRASS8
python simulate_FG_BG_only.py 664 eRASS8
python simulate_FG_BG_only.py 665 eRASS8
python simulate_FG_BG_only.py 666 eRASS8
python simulate_FG_BG_only.py 667 eRASS8
python simulate_FG_BG_only.py 668 eRASS8
python simulate_FG_BG_only.py 669 eRASS8
python simulate_FG_BG_only.py 670 eRASS8
python simulate_FG_BG_only.py 671 eRASS8
python simulate_FG_BG_only.py 672 eRASS8
python simulate_FG_BG_only.py 673 eRASS8
python simulate_FG_BG_only.py 674 eRASS8
python simulate_FG_BG_only.py 675 eRASS8
python simulate_FG_BG_only.py 676 eRASS8
python simulate_FG_BG_only.py 677 eRASS8
python simulate_FG_BG_only.py 678 eRASS8
python simulate_FG_BG_only.py 679 eRASS8
python simulate_FG_BG_only.py 680 eRASS8
python simulate_FG_BG_only.py 681 eRASS8
python simulate_FG_BG_only.py 682 eRASS8
python simulate_FG_BG_only.py 683 eRASS8
python simulate_FG_BG_only.py 684 eRASS8
python simulate_FG_BG_only.py 685 eRASS8
python simulate_FG_BG_only.py 686 eRASS8
python simulate_FG_BG_only.py 687 eRASS8
python simulate_FG_BG_only.py 688 eRASS8
python simulate_FG_BG_only.py 689 eRASS8
python simulate_FG_BG_only.py 690 eRASS8
python simulate_FG_BG_only.py 691 eRASS8
python simulate_FG_BG_only.py 692 eRASS8
python simulate_FG_BG_only.py 693 eRASS8
python simulate_FG_BG_only.py 694 eRASS8
python simulate_FG_BG_only.py 695 eRASS8
python simulate_FG_BG_only.py 696 eRASS8
python simulate_FG_BG_only.py 697 eRASS8
python simulate_FG_BG_only.py 698 eRASS8
python simulate_FG_BG_only.py 699 eRASS8

python simulate_FG_BG_only.py 700 eRASS8
python simulate_FG_BG_only.py 701 eRASS8
python simulate_FG_BG_only.py 702 eRASS8
python simulate_FG_BG_only.py 703 eRASS8
python simulate_FG_BG_only.py 704 eRASS8
python simulate_FG_BG_only.py 705 eRASS8
python simulate_FG_BG_only.py 706 eRASS8
python simulate_FG_BG_only.py 707 eRASS8
python simulate_FG_BG_only.py 708 eRASS8
python simulate_FG_BG_only.py 709 eRASS8
python simulate_FG_BG_only.py 710 eRASS8
python simulate_FG_BG_only.py 711 eRASS8
python simulate_FG_BG_only.py 712 eRASS8
python simulate_FG_BG_only.py 713 eRASS8
python simulate_FG_BG_only.py 714 eRASS8
python simulate_FG_BG_only.py 715 eRASS8
python simulate_FG_BG_only.py 716 eRASS8
python simulate_FG_BG_only.py 717 eRASS8
python simulate_FG_BG_only.py 718 eRASS8
python simulate_FG_BG_only.py 719 eRASS8
python simulate_FG_BG_only.py 720 eRASS8
python simulate_FG_BG_only.py 721 eRASS8
python simulate_FG_BG_only.py 722 eRASS8
python simulate_FG_BG_only.py 723 eRASS8
python simulate_FG_BG_only.py 724 eRASS8
python simulate_FG_BG_only.py 725 eRASS8
python simulate_FG_BG_only.py 726 eRASS8
python simulate_FG_BG_only.py 727 eRASS8
python simulate_FG_BG_only.py 728 eRASS8
python simulate_FG_BG_only.py 729 eRASS8
python simulate_FG_BG_only.py 730 eRASS8
python simulate_FG_BG_only.py 731 eRASS8
python simulate_FG_BG_only.py 732 eRASS8
python simulate_FG_BG_only.py 733 eRASS8
python simulate_FG_BG_only.py 734 eRASS8
python simulate_FG_BG_only.py 735 eRASS8
python simulate_FG_BG_only.py 736 eRASS8
python simulate_FG_BG_only.py 737 eRASS8
python simulate_FG_BG_only.py 738 eRASS8
python simulate_FG_BG_only.py 739 eRASS8
python simulate_FG_BG_only.py 740 eRASS8
python simulate_FG_BG_only.py 741 eRASS8
python simulate_FG_BG_only.py 742 eRASS8
python simulate_FG_BG_only.py 743 eRASS8
python simulate_FG_BG_only.py 744 eRASS8
python simulate_FG_BG_only.py 745 eRASS8
python simulate_FG_BG_only.py 746 eRASS8
python simulate_FG_BG_only.py 747 eRASS8
python simulate_FG_BG_only.py 748 eRASS8
python simulate_FG_BG_only.py 749 eRASS8
python simulate_FG_BG_only.py 750 eRASS8
python simulate_FG_BG_only.py 751 eRASS8
python simulate_FG_BG_only.py 752 eRASS8
python simulate_FG_BG_only.py 753 eRASS8
python simulate_FG_BG_only.py 754 eRASS8
python simulate_FG_BG_only.py 755 eRASS8
python simulate_FG_BG_only.py 756 eRASS8
python simulate_FG_BG_only.py 757 eRASS8
python simulate_FG_BG_only.py 758 eRASS8
python simulate_FG_BG_only.py 759 eRASS8
python simulate_FG_BG_only.py 760 eRASS8
python simulate_FG_BG_only.py 761 eRASS8
python simulate_FG_BG_only.py 762 eRASS8
python simulate_FG_BG_only.py 763 eRASS8
python simulate_FG_BG_only.py 764 eRASS8
python simulate_FG_BG_only.py 765 eRASS8
python simulate_FG_BG_only.py 766 eRASS8
python simulate_FG_BG_only.py 767 eRASS8

