#!/bin/bash/

# python simulate_FG_BG_only.py 000 eRASS8
python simulate_FG_BG_only.py 001 eRASS8
python simulate_FG_BG_only.py 002 eRASS8
python simulate_FG_BG_only.py 003 eRASS8
python simulate_FG_BG_only.py 004 eRASS8
python simulate_FG_BG_only.py 005 eRASS8
python simulate_FG_BG_only.py 006 eRASS8
python simulate_FG_BG_only.py 007 eRASS8
python simulate_FG_BG_only.py 008 eRASS8
python simulate_FG_BG_only.py 009 eRASS8
python simulate_FG_BG_only.py 010 eRASS8
python simulate_FG_BG_only.py 011 eRASS8
python simulate_FG_BG_only.py 012 eRASS8
python simulate_FG_BG_only.py 013 eRASS8
python simulate_FG_BG_only.py 014 eRASS8
python simulate_FG_BG_only.py 015 eRASS8
python simulate_FG_BG_only.py 016 eRASS8
python simulate_FG_BG_only.py 017 eRASS8
python simulate_FG_BG_only.py 018 eRASS8
python simulate_FG_BG_only.py 019 eRASS8
python simulate_FG_BG_only.py 020 eRASS8
python simulate_FG_BG_only.py 021 eRASS8
python simulate_FG_BG_only.py 022 eRASS8
python simulate_FG_BG_only.py 023 eRASS8
python simulate_FG_BG_only.py 024 eRASS8
python simulate_FG_BG_only.py 025 eRASS8
python simulate_FG_BG_only.py 026 eRASS8
python simulate_FG_BG_only.py 027 eRASS8
python simulate_FG_BG_only.py 028 eRASS8
python simulate_FG_BG_only.py 029 eRASS8
python simulate_FG_BG_only.py 030 eRASS8
python simulate_FG_BG_only.py 031 eRASS8
python simulate_FG_BG_only.py 032 eRASS8
python simulate_FG_BG_only.py 033 eRASS8
python simulate_FG_BG_only.py 034 eRASS8
python simulate_FG_BG_only.py 035 eRASS8
python simulate_FG_BG_only.py 036 eRASS8
python simulate_FG_BG_only.py 037 eRASS8
python simulate_FG_BG_only.py 038 eRASS8
python simulate_FG_BG_only.py 039 eRASS8
python simulate_FG_BG_only.py 040 eRASS8
python simulate_FG_BG_only.py 041 eRASS8
python simulate_FG_BG_only.py 042 eRASS8
python simulate_FG_BG_only.py 043 eRASS8
python simulate_FG_BG_only.py 044 eRASS8
python simulate_FG_BG_only.py 045 eRASS8
python simulate_FG_BG_only.py 046 eRASS8
python simulate_FG_BG_only.py 047 eRASS8
python simulate_FG_BG_only.py 048 eRASS8
python simulate_FG_BG_only.py 049 eRASS8
python simulate_FG_BG_only.py 050 eRASS8
python simulate_FG_BG_only.py 051 eRASS8
python simulate_FG_BG_only.py 052 eRASS8
python simulate_FG_BG_only.py 053 eRASS8
python simulate_FG_BG_only.py 054 eRASS8
python simulate_FG_BG_only.py 055 eRASS8
python simulate_FG_BG_only.py 056 eRASS8
python simulate_FG_BG_only.py 057 eRASS8
python simulate_FG_BG_only.py 058 eRASS8
python simulate_FG_BG_only.py 059 eRASS8
python simulate_FG_BG_only.py 060 eRASS8
python simulate_FG_BG_only.py 061 eRASS8
python simulate_FG_BG_only.py 062 eRASS8
python simulate_FG_BG_only.py 063 eRASS8
python simulate_FG_BG_only.py 064 eRASS8
python simulate_FG_BG_only.py 065 eRASS8
python simulate_FG_BG_only.py 066 eRASS8
python simulate_FG_BG_only.py 067 eRASS8
python simulate_FG_BG_only.py 068 eRASS8
python simulate_FG_BG_only.py 069 eRASS8
python simulate_FG_BG_only.py 070 eRASS8
python simulate_FG_BG_only.py 071 eRASS8
python simulate_FG_BG_only.py 072 eRASS8
python simulate_FG_BG_only.py 073 eRASS8
python simulate_FG_BG_only.py 074 eRASS8
python simulate_FG_BG_only.py 075 eRASS8
python simulate_FG_BG_only.py 076 eRASS8
python simulate_FG_BG_only.py 077 eRASS8
python simulate_FG_BG_only.py 078 eRASS8
python simulate_FG_BG_only.py 079 eRASS8
python simulate_FG_BG_only.py 080 eRASS8
python simulate_FG_BG_only.py 081 eRASS8
python simulate_FG_BG_only.py 082 eRASS8
python simulate_FG_BG_only.py 083 eRASS8
python simulate_FG_BG_only.py 084 eRASS8
python simulate_FG_BG_only.py 085 eRASS8
python simulate_FG_BG_only.py 086 eRASS8
python simulate_FG_BG_only.py 087 eRASS8
python simulate_FG_BG_only.py 088 eRASS8
python simulate_FG_BG_only.py 089 eRASS8
python simulate_FG_BG_only.py 090 eRASS8
python simulate_FG_BG_only.py 091 eRASS8
python simulate_FG_BG_only.py 092 eRASS8
python simulate_FG_BG_only.py 093 eRASS8
python simulate_FG_BG_only.py 094 eRASS8
python simulate_FG_BG_only.py 095 eRASS8
python simulate_FG_BG_only.py 096 eRASS8
python simulate_FG_BG_only.py 097 eRASS8
python simulate_FG_BG_only.py 098 eRASS8
python simulate_FG_BG_only.py 099 eRASS8

