#!/bin/bash/
  
python simulate_FG_BG_only.py 200 eRASS8
python simulate_FG_BG_only.py 201 eRASS8
python simulate_FG_BG_only.py 202 eRASS8
python simulate_FG_BG_only.py 203 eRASS8
python simulate_FG_BG_only.py 204 eRASS8
python simulate_FG_BG_only.py 205 eRASS8
python simulate_FG_BG_only.py 206 eRASS8
python simulate_FG_BG_only.py 207 eRASS8
python simulate_FG_BG_only.py 208 eRASS8
python simulate_FG_BG_only.py 209 eRASS8
python simulate_FG_BG_only.py 210 eRASS8
python simulate_FG_BG_only.py 211 eRASS8
python simulate_FG_BG_only.py 212 eRASS8
python simulate_FG_BG_only.py 213 eRASS8
python simulate_FG_BG_only.py 214 eRASS8
python simulate_FG_BG_only.py 215 eRASS8
python simulate_FG_BG_only.py 216 eRASS8
python simulate_FG_BG_only.py 217 eRASS8
python simulate_FG_BG_only.py 218 eRASS8
python simulate_FG_BG_only.py 219 eRASS8
python simulate_FG_BG_only.py 220 eRASS8
python simulate_FG_BG_only.py 221 eRASS8
python simulate_FG_BG_only.py 222 eRASS8
python simulate_FG_BG_only.py 223 eRASS8
python simulate_FG_BG_only.py 224 eRASS8
python simulate_FG_BG_only.py 225 eRASS8
python simulate_FG_BG_only.py 226 eRASS8
python simulate_FG_BG_only.py 227 eRASS8
python simulate_FG_BG_only.py 228 eRASS8
python simulate_FG_BG_only.py 229 eRASS8
python simulate_FG_BG_only.py 230 eRASS8
python simulate_FG_BG_only.py 231 eRASS8
python simulate_FG_BG_only.py 232 eRASS8
python simulate_FG_BG_only.py 233 eRASS8
python simulate_FG_BG_only.py 234 eRASS8
python simulate_FG_BG_only.py 235 eRASS8
python simulate_FG_BG_only.py 236 eRASS8
python simulate_FG_BG_only.py 237 eRASS8
python simulate_FG_BG_only.py 238 eRASS8
python simulate_FG_BG_only.py 239 eRASS8
python simulate_FG_BG_only.py 240 eRASS8
python simulate_FG_BG_only.py 241 eRASS8
python simulate_FG_BG_only.py 242 eRASS8
python simulate_FG_BG_only.py 243 eRASS8
python simulate_FG_BG_only.py 244 eRASS8
python simulate_FG_BG_only.py 245 eRASS8
python simulate_FG_BG_only.py 246 eRASS8
python simulate_FG_BG_only.py 247 eRASS8
python simulate_FG_BG_only.py 248 eRASS8
python simulate_FG_BG_only.py 249 eRASS8
python simulate_FG_BG_only.py 250 eRASS8
python simulate_FG_BG_only.py 251 eRASS8
python simulate_FG_BG_only.py 252 eRASS8
python simulate_FG_BG_only.py 253 eRASS8
python simulate_FG_BG_only.py 254 eRASS8
python simulate_FG_BG_only.py 255 eRASS8
python simulate_FG_BG_only.py 256 eRASS8
python simulate_FG_BG_only.py 257 eRASS8
python simulate_FG_BG_only.py 258 eRASS8
python simulate_FG_BG_only.py 259 eRASS8
python simulate_FG_BG_only.py 260 eRASS8
python simulate_FG_BG_only.py 261 eRASS8
python simulate_FG_BG_only.py 262 eRASS8
python simulate_FG_BG_only.py 263 eRASS8
python simulate_FG_BG_only.py 264 eRASS8
python simulate_FG_BG_only.py 265 eRASS8
python simulate_FG_BG_only.py 266 eRASS8
python simulate_FG_BG_only.py 267 eRASS8
python simulate_FG_BG_only.py 268 eRASS8
python simulate_FG_BG_only.py 269 eRASS8
python simulate_FG_BG_only.py 270 eRASS8
python simulate_FG_BG_only.py 271 eRASS8
python simulate_FG_BG_only.py 272 eRASS8
python simulate_FG_BG_only.py 273 eRASS8
python simulate_FG_BG_only.py 274 eRASS8
python simulate_FG_BG_only.py 275 eRASS8
python simulate_FG_BG_only.py 276 eRASS8
python simulate_FG_BG_only.py 277 eRASS8
python simulate_FG_BG_only.py 278 eRASS8
python simulate_FG_BG_only.py 279 eRASS8
python simulate_FG_BG_only.py 280 eRASS8
python simulate_FG_BG_only.py 281 eRASS8
python simulate_FG_BG_only.py 282 eRASS8
python simulate_FG_BG_only.py 283 eRASS8
python simulate_FG_BG_only.py 284 eRASS8
python simulate_FG_BG_only.py 285 eRASS8
python simulate_FG_BG_only.py 286 eRASS8
python simulate_FG_BG_only.py 287 eRASS8
python simulate_FG_BG_only.py 288 eRASS8
python simulate_FG_BG_only.py 289 eRASS8
python simulate_FG_BG_only.py 290 eRASS8
python simulate_FG_BG_only.py 291 eRASS8
python simulate_FG_BG_only.py 292 eRASS8
python simulate_FG_BG_only.py 293 eRASS8
python simulate_FG_BG_only.py 294 eRASS8
python simulate_FG_BG_only.py 295 eRASS8
python simulate_FG_BG_only.py 296 eRASS8
python simulate_FG_BG_only.py 297 eRASS8
python simulate_FG_BG_only.py 298 eRASS8
python simulate_FG_BG_only.py 299 eRASS8
            
