#!/bin/bash/
       
python simulate_FG_BG_only.py 400 eRASS8
python simulate_FG_BG_only.py 401 eRASS8
python simulate_FG_BG_only.py 402 eRASS8
python simulate_FG_BG_only.py 403 eRASS8
python simulate_FG_BG_only.py 404 eRASS8
python simulate_FG_BG_only.py 405 eRASS8
python simulate_FG_BG_only.py 406 eRASS8
python simulate_FG_BG_only.py 407 eRASS8
python simulate_FG_BG_only.py 408 eRASS8
python simulate_FG_BG_only.py 409 eRASS8
python simulate_FG_BG_only.py 410 eRASS8
python simulate_FG_BG_only.py 411 eRASS8
python simulate_FG_BG_only.py 412 eRASS8
python simulate_FG_BG_only.py 413 eRASS8
python simulate_FG_BG_only.py 414 eRASS8
python simulate_FG_BG_only.py 415 eRASS8
python simulate_FG_BG_only.py 416 eRASS8
python simulate_FG_BG_only.py 417 eRASS8
python simulate_FG_BG_only.py 418 eRASS8
python simulate_FG_BG_only.py 419 eRASS8
python simulate_FG_BG_only.py 420 eRASS8
python simulate_FG_BG_only.py 421 eRASS8
python simulate_FG_BG_only.py 422 eRASS8
python simulate_FG_BG_only.py 423 eRASS8
python simulate_FG_BG_only.py 424 eRASS8
python simulate_FG_BG_only.py 425 eRASS8
python simulate_FG_BG_only.py 426 eRASS8
python simulate_FG_BG_only.py 427 eRASS8
python simulate_FG_BG_only.py 428 eRASS8
python simulate_FG_BG_only.py 429 eRASS8
python simulate_FG_BG_only.py 430 eRASS8
python simulate_FG_BG_only.py 431 eRASS8
python simulate_FG_BG_only.py 432 eRASS8
python simulate_FG_BG_only.py 433 eRASS8
python simulate_FG_BG_only.py 434 eRASS8
python simulate_FG_BG_only.py 435 eRASS8
python simulate_FG_BG_only.py 436 eRASS8
python simulate_FG_BG_only.py 437 eRASS8
python simulate_FG_BG_only.py 438 eRASS8
python simulate_FG_BG_only.py 439 eRASS8
python simulate_FG_BG_only.py 440 eRASS8
python simulate_FG_BG_only.py 441 eRASS8
python simulate_FG_BG_only.py 442 eRASS8
python simulate_FG_BG_only.py 443 eRASS8
python simulate_FG_BG_only.py 444 eRASS8
python simulate_FG_BG_only.py 445 eRASS8
python simulate_FG_BG_only.py 446 eRASS8
python simulate_FG_BG_only.py 447 eRASS8
python simulate_FG_BG_only.py 448 eRASS8
python simulate_FG_BG_only.py 449 eRASS8
python simulate_FG_BG_only.py 450 eRASS8
python simulate_FG_BG_only.py 451 eRASS8
python simulate_FG_BG_only.py 452 eRASS8
python simulate_FG_BG_only.py 453 eRASS8
python simulate_FG_BG_only.py 454 eRASS8
python simulate_FG_BG_only.py 455 eRASS8
python simulate_FG_BG_only.py 456 eRASS8
python simulate_FG_BG_only.py 457 eRASS8
python simulate_FG_BG_only.py 458 eRASS8
python simulate_FG_BG_only.py 459 eRASS8
python simulate_FG_BG_only.py 460 eRASS8
python simulate_FG_BG_only.py 461 eRASS8
python simulate_FG_BG_only.py 462 eRASS8
python simulate_FG_BG_only.py 463 eRASS8
python simulate_FG_BG_only.py 464 eRASS8
python simulate_FG_BG_only.py 465 eRASS8
python simulate_FG_BG_only.py 466 eRASS8
python simulate_FG_BG_only.py 467 eRASS8
python simulate_FG_BG_only.py 468 eRASS8
python simulate_FG_BG_only.py 469 eRASS8
python simulate_FG_BG_only.py 470 eRASS8
python simulate_FG_BG_only.py 471 eRASS8
python simulate_FG_BG_only.py 472 eRASS8
python simulate_FG_BG_only.py 473 eRASS8
python simulate_FG_BG_only.py 474 eRASS8
python simulate_FG_BG_only.py 475 eRASS8
python simulate_FG_BG_only.py 476 eRASS8
python simulate_FG_BG_only.py 477 eRASS8
python simulate_FG_BG_only.py 478 eRASS8
python simulate_FG_BG_only.py 479 eRASS8
python simulate_FG_BG_only.py 480 eRASS8
python simulate_FG_BG_only.py 481 eRASS8
python simulate_FG_BG_only.py 482 eRASS8
python simulate_FG_BG_only.py 483 eRASS8
python simulate_FG_BG_only.py 484 eRASS8
python simulate_FG_BG_only.py 485 eRASS8
python simulate_FG_BG_only.py 486 eRASS8
python simulate_FG_BG_only.py 487 eRASS8
python simulate_FG_BG_only.py 488 eRASS8
python simulate_FG_BG_only.py 489 eRASS8
python simulate_FG_BG_only.py 490 eRASS8
python simulate_FG_BG_only.py 491 eRASS8
python simulate_FG_BG_only.py 492 eRASS8
python simulate_FG_BG_only.py 493 eRASS8
python simulate_FG_BG_only.py 494 eRASS8
python simulate_FG_BG_only.py 495 eRASS8
python simulate_FG_BG_only.py 496 eRASS8
python simulate_FG_BG_only.py 497 eRASS8
python simulate_FG_BG_only.py 498 eRASS8
python simulate_FG_BG_only.py 499 eRASS8
                                      

