#!/bin/bash/
             
python simulate_FG_BG_only.py 500 eRASS8
python simulate_FG_BG_only.py 501 eRASS8
python simulate_FG_BG_only.py 502 eRASS8
python simulate_FG_BG_only.py 503 eRASS8
python simulate_FG_BG_only.py 504 eRASS8
python simulate_FG_BG_only.py 505 eRASS8
python simulate_FG_BG_only.py 506 eRASS8
python simulate_FG_BG_only.py 507 eRASS8
python simulate_FG_BG_only.py 508 eRASS8
python simulate_FG_BG_only.py 509 eRASS8
python simulate_FG_BG_only.py 510 eRASS8
python simulate_FG_BG_only.py 511 eRASS8
python simulate_FG_BG_only.py 512 eRASS8
python simulate_FG_BG_only.py 513 eRASS8
python simulate_FG_BG_only.py 514 eRASS8
python simulate_FG_BG_only.py 515 eRASS8
python simulate_FG_BG_only.py 516 eRASS8
python simulate_FG_BG_only.py 517 eRASS8
python simulate_FG_BG_only.py 518 eRASS8
python simulate_FG_BG_only.py 519 eRASS8
python simulate_FG_BG_only.py 520 eRASS8
python simulate_FG_BG_only.py 521 eRASS8
python simulate_FG_BG_only.py 522 eRASS8
python simulate_FG_BG_only.py 523 eRASS8
python simulate_FG_BG_only.py 524 eRASS8
python simulate_FG_BG_only.py 525 eRASS8
python simulate_FG_BG_only.py 526 eRASS8
python simulate_FG_BG_only.py 527 eRASS8
python simulate_FG_BG_only.py 528 eRASS8
python simulate_FG_BG_only.py 529 eRASS8
python simulate_FG_BG_only.py 530 eRASS8
python simulate_FG_BG_only.py 531 eRASS8
python simulate_FG_BG_only.py 532 eRASS8
python simulate_FG_BG_only.py 533 eRASS8
python simulate_FG_BG_only.py 534 eRASS8
python simulate_FG_BG_only.py 535 eRASS8
python simulate_FG_BG_only.py 536 eRASS8
python simulate_FG_BG_only.py 537 eRASS8
python simulate_FG_BG_only.py 538 eRASS8
python simulate_FG_BG_only.py 539 eRASS8
python simulate_FG_BG_only.py 540 eRASS8
python simulate_FG_BG_only.py 541 eRASS8
python simulate_FG_BG_only.py 542 eRASS8
python simulate_FG_BG_only.py 543 eRASS8
python simulate_FG_BG_only.py 544 eRASS8
python simulate_FG_BG_only.py 545 eRASS8
python simulate_FG_BG_only.py 546 eRASS8
python simulate_FG_BG_only.py 547 eRASS8
python simulate_FG_BG_only.py 548 eRASS8
python simulate_FG_BG_only.py 549 eRASS8
python simulate_FG_BG_only.py 550 eRASS8
python simulate_FG_BG_only.py 551 eRASS8
python simulate_FG_BG_only.py 552 eRASS8
python simulate_FG_BG_only.py 553 eRASS8
python simulate_FG_BG_only.py 554 eRASS8
python simulate_FG_BG_only.py 555 eRASS8
python simulate_FG_BG_only.py 556 eRASS8
python simulate_FG_BG_only.py 557 eRASS8
python simulate_FG_BG_only.py 558 eRASS8
python simulate_FG_BG_only.py 559 eRASS8
python simulate_FG_BG_only.py 560 eRASS8
python simulate_FG_BG_only.py 561 eRASS8
python simulate_FG_BG_only.py 562 eRASS8
python simulate_FG_BG_only.py 563 eRASS8
python simulate_FG_BG_only.py 564 eRASS8
python simulate_FG_BG_only.py 565 eRASS8
python simulate_FG_BG_only.py 566 eRASS8
python simulate_FG_BG_only.py 567 eRASS8
python simulate_FG_BG_only.py 568 eRASS8
python simulate_FG_BG_only.py 569 eRASS8
python simulate_FG_BG_only.py 570 eRASS8
python simulate_FG_BG_only.py 571 eRASS8
python simulate_FG_BG_only.py 572 eRASS8
python simulate_FG_BG_only.py 573 eRASS8
python simulate_FG_BG_only.py 574 eRASS8
python simulate_FG_BG_only.py 575 eRASS8
python simulate_FG_BG_only.py 576 eRASS8
python simulate_FG_BG_only.py 577 eRASS8
python simulate_FG_BG_only.py 578 eRASS8
python simulate_FG_BG_only.py 579 eRASS8
python simulate_FG_BG_only.py 580 eRASS8
python simulate_FG_BG_only.py 581 eRASS8
python simulate_FG_BG_only.py 582 eRASS8
python simulate_FG_BG_only.py 583 eRASS8
python simulate_FG_BG_only.py 584 eRASS8
python simulate_FG_BG_only.py 585 eRASS8
python simulate_FG_BG_only.py 586 eRASS8
python simulate_FG_BG_only.py 587 eRASS8
python simulate_FG_BG_only.py 588 eRASS8
python simulate_FG_BG_only.py 589 eRASS8
python simulate_FG_BG_only.py 590 eRASS8
python simulate_FG_BG_only.py 591 eRASS8
python simulate_FG_BG_only.py 592 eRASS8
python simulate_FG_BG_only.py 593 eRASS8
python simulate_FG_BG_only.py 594 eRASS8
python simulate_FG_BG_only.py 595 eRASS8
python simulate_FG_BG_only.py 596 eRASS8
python simulate_FG_BG_only.py 597 eRASS8
python simulate_FG_BG_only.py 598 eRASS8
python simulate_FG_BG_only.py 599 eRASS8
