#!/bin/bash/

                           
python simulate_FG_BG_only.py 100 eRASS8
python simulate_FG_BG_only.py 101 eRASS8
python simulate_FG_BG_only.py 102 eRASS8
python simulate_FG_BG_only.py 103 eRASS8
python simulate_FG_BG_only.py 104 eRASS8
python simulate_FG_BG_only.py 105 eRASS8
python simulate_FG_BG_only.py 106 eRASS8
python simulate_FG_BG_only.py 107 eRASS8
python simulate_FG_BG_only.py 108 eRASS8
python simulate_FG_BG_only.py 109 eRASS8
python simulate_FG_BG_only.py 110 eRASS8
python simulate_FG_BG_only.py 111 eRASS8
python simulate_FG_BG_only.py 112 eRASS8
python simulate_FG_BG_only.py 113 eRASS8
python simulate_FG_BG_only.py 114 eRASS8
python simulate_FG_BG_only.py 115 eRASS8
python simulate_FG_BG_only.py 116 eRASS8
python simulate_FG_BG_only.py 117 eRASS8
python simulate_FG_BG_only.py 118 eRASS8
python simulate_FG_BG_only.py 119 eRASS8
python simulate_FG_BG_only.py 120 eRASS8
python simulate_FG_BG_only.py 121 eRASS8
python simulate_FG_BG_only.py 122 eRASS8
python simulate_FG_BG_only.py 123 eRASS8
python simulate_FG_BG_only.py 124 eRASS8
python simulate_FG_BG_only.py 125 eRASS8
python simulate_FG_BG_only.py 126 eRASS8
python simulate_FG_BG_only.py 127 eRASS8
python simulate_FG_BG_only.py 128 eRASS8
python simulate_FG_BG_only.py 129 eRASS8
python simulate_FG_BG_only.py 130 eRASS8
python simulate_FG_BG_only.py 131 eRASS8
python simulate_FG_BG_only.py 132 eRASS8
python simulate_FG_BG_only.py 133 eRASS8
python simulate_FG_BG_only.py 134 eRASS8
python simulate_FG_BG_only.py 135 eRASS8
python simulate_FG_BG_only.py 136 eRASS8
python simulate_FG_BG_only.py 137 eRASS8
python simulate_FG_BG_only.py 138 eRASS8
python simulate_FG_BG_only.py 139 eRASS8
python simulate_FG_BG_only.py 140 eRASS8
python simulate_FG_BG_only.py 141 eRASS8
python simulate_FG_BG_only.py 142 eRASS8
python simulate_FG_BG_only.py 143 eRASS8
python simulate_FG_BG_only.py 144 eRASS8
python simulate_FG_BG_only.py 145 eRASS8
python simulate_FG_BG_only.py 146 eRASS8
python simulate_FG_BG_only.py 147 eRASS8
python simulate_FG_BG_only.py 148 eRASS8
python simulate_FG_BG_only.py 149 eRASS8
python simulate_FG_BG_only.py 150 eRASS8
python simulate_FG_BG_only.py 151 eRASS8
python simulate_FG_BG_only.py 152 eRASS8
python simulate_FG_BG_only.py 153 eRASS8
python simulate_FG_BG_only.py 154 eRASS8
python simulate_FG_BG_only.py 155 eRASS8
python simulate_FG_BG_only.py 156 eRASS8
python simulate_FG_BG_only.py 157 eRASS8
python simulate_FG_BG_only.py 158 eRASS8
python simulate_FG_BG_only.py 159 eRASS8
python simulate_FG_BG_only.py 160 eRASS8
python simulate_FG_BG_only.py 161 eRASS8
python simulate_FG_BG_only.py 162 eRASS8
python simulate_FG_BG_only.py 163 eRASS8
python simulate_FG_BG_only.py 164 eRASS8
python simulate_FG_BG_only.py 165 eRASS8
python simulate_FG_BG_only.py 166 eRASS8
python simulate_FG_BG_only.py 167 eRASS8
python simulate_FG_BG_only.py 168 eRASS8
python simulate_FG_BG_only.py 169 eRASS8
python simulate_FG_BG_only.py 170 eRASS8
python simulate_FG_BG_only.py 171 eRASS8
python simulate_FG_BG_only.py 172 eRASS8
python simulate_FG_BG_only.py 173 eRASS8
python simulate_FG_BG_only.py 174 eRASS8
python simulate_FG_BG_only.py 175 eRASS8
python simulate_FG_BG_only.py 176 eRASS8
python simulate_FG_BG_only.py 177 eRASS8
python simulate_FG_BG_only.py 178 eRASS8
python simulate_FG_BG_only.py 179 eRASS8
python simulate_FG_BG_only.py 180 eRASS8
python simulate_FG_BG_only.py 181 eRASS8
python simulate_FG_BG_only.py 182 eRASS8
python simulate_FG_BG_only.py 183 eRASS8
python simulate_FG_BG_only.py 184 eRASS8
python simulate_FG_BG_only.py 185 eRASS8
python simulate_FG_BG_only.py 186 eRASS8
python simulate_FG_BG_only.py 187 eRASS8
python simulate_FG_BG_only.py 188 eRASS8
python simulate_FG_BG_only.py 189 eRASS8
python simulate_FG_BG_only.py 190 eRASS8
python simulate_FG_BG_only.py 191 eRASS8
python simulate_FG_BG_only.py 192 eRASS8
python simulate_FG_BG_only.py 193 eRASS8
python simulate_FG_BG_only.py 194 eRASS8
python simulate_FG_BG_only.py 195 eRASS8
python simulate_FG_BG_only.py 196 eRASS8
python simulate_FG_BG_only.py 197 eRASS8
python simulate_FG_BG_only.py 198 eRASS8
python simulate_FG_BG_only.py 199 eRASS8
                                      
