#!/bin/bash/
     
python simulate_FG_BG_only.py 300 eRASS8
python simulate_FG_BG_only.py 301 eRASS8
python simulate_FG_BG_only.py 302 eRASS8
python simulate_FG_BG_only.py 303 eRASS8
python simulate_FG_BG_only.py 304 eRASS8
python simulate_FG_BG_only.py 305 eRASS8
python simulate_FG_BG_only.py 306 eRASS8
python simulate_FG_BG_only.py 307 eRASS8
python simulate_FG_BG_only.py 308 eRASS8
python simulate_FG_BG_only.py 309 eRASS8
python simulate_FG_BG_only.py 310 eRASS8
python simulate_FG_BG_only.py 311 eRASS8
python simulate_FG_BG_only.py 312 eRASS8
python simulate_FG_BG_only.py 313 eRASS8
python simulate_FG_BG_only.py 314 eRASS8
python simulate_FG_BG_only.py 315 eRASS8
python simulate_FG_BG_only.py 316 eRASS8
python simulate_FG_BG_only.py 317 eRASS8
python simulate_FG_BG_only.py 318 eRASS8
python simulate_FG_BG_only.py 319 eRASS8
python simulate_FG_BG_only.py 320 eRASS8
python simulate_FG_BG_only.py 321 eRASS8
python simulate_FG_BG_only.py 322 eRASS8
python simulate_FG_BG_only.py 323 eRASS8
python simulate_FG_BG_only.py 324 eRASS8
python simulate_FG_BG_only.py 325 eRASS8
python simulate_FG_BG_only.py 326 eRASS8
python simulate_FG_BG_only.py 327 eRASS8
python simulate_FG_BG_only.py 328 eRASS8
python simulate_FG_BG_only.py 329 eRASS8
python simulate_FG_BG_only.py 330 eRASS8
python simulate_FG_BG_only.py 331 eRASS8
python simulate_FG_BG_only.py 332 eRASS8
python simulate_FG_BG_only.py 333 eRASS8
python simulate_FG_BG_only.py 334 eRASS8
python simulate_FG_BG_only.py 335 eRASS8
python simulate_FG_BG_only.py 336 eRASS8
python simulate_FG_BG_only.py 337 eRASS8
python simulate_FG_BG_only.py 338 eRASS8
python simulate_FG_BG_only.py 339 eRASS8
python simulate_FG_BG_only.py 340 eRASS8
python simulate_FG_BG_only.py 341 eRASS8
python simulate_FG_BG_only.py 342 eRASS8
python simulate_FG_BG_only.py 343 eRASS8
python simulate_FG_BG_only.py 344 eRASS8
python simulate_FG_BG_only.py 345 eRASS8
python simulate_FG_BG_only.py 346 eRASS8
python simulate_FG_BG_only.py 347 eRASS8
python simulate_FG_BG_only.py 348 eRASS8
python simulate_FG_BG_only.py 349 eRASS8
python simulate_FG_BG_only.py 350 eRASS8
python simulate_FG_BG_only.py 351 eRASS8
python simulate_FG_BG_only.py 352 eRASS8
python simulate_FG_BG_only.py 353 eRASS8
python simulate_FG_BG_only.py 354 eRASS8
python simulate_FG_BG_only.py 355 eRASS8
python simulate_FG_BG_only.py 356 eRASS8
python simulate_FG_BG_only.py 357 eRASS8
python simulate_FG_BG_only.py 358 eRASS8
python simulate_FG_BG_only.py 359 eRASS8
python simulate_FG_BG_only.py 360 eRASS8
python simulate_FG_BG_only.py 361 eRASS8
python simulate_FG_BG_only.py 362 eRASS8
python simulate_FG_BG_only.py 363 eRASS8
python simulate_FG_BG_only.py 364 eRASS8
python simulate_FG_BG_only.py 365 eRASS8
python simulate_FG_BG_only.py 366 eRASS8
python simulate_FG_BG_only.py 367 eRASS8
python simulate_FG_BG_only.py 368 eRASS8
python simulate_FG_BG_only.py 369 eRASS8
python simulate_FG_BG_only.py 370 eRASS8
python simulate_FG_BG_only.py 371 eRASS8
python simulate_FG_BG_only.py 372 eRASS8
python simulate_FG_BG_only.py 373 eRASS8
python simulate_FG_BG_only.py 374 eRASS8
python simulate_FG_BG_only.py 375 eRASS8
python simulate_FG_BG_only.py 376 eRASS8
python simulate_FG_BG_only.py 377 eRASS8
python simulate_FG_BG_only.py 378 eRASS8
python simulate_FG_BG_only.py 379 eRASS8
python simulate_FG_BG_only.py 380 eRASS8
python simulate_FG_BG_only.py 381 eRASS8
python simulate_FG_BG_only.py 382 eRASS8
python simulate_FG_BG_only.py 383 eRASS8
python simulate_FG_BG_only.py 384 eRASS8
python simulate_FG_BG_only.py 385 eRASS8
python simulate_FG_BG_only.py 386 eRASS8
python simulate_FG_BG_only.py 387 eRASS8
python simulate_FG_BG_only.py 388 eRASS8
python simulate_FG_BG_only.py 389 eRASS8
python simulate_FG_BG_only.py 390 eRASS8
python simulate_FG_BG_only.py 391 eRASS8
python simulate_FG_BG_only.py 392 eRASS8
python simulate_FG_BG_only.py 393 eRASS8
python simulate_FG_BG_only.py 394 eRASS8
python simulate_FG_BG_only.py 395 eRASS8
python simulate_FG_BG_only.py 396 eRASS8
python simulate_FG_BG_only.py 397 eRASS8
python simulate_FG_BG_only.py 398 eRASS8
python simulate_FG_BG_only.py 399 eRASS8
                 
