#!/bin/bash
python AGN_setup.py 0   #> AGN_logs/AGN_LX_table_0.log &
python AGN_setup.py 1   #> AGN_logs/AGN_LX_table_1.log &
python AGN_setup.py 2   #> AGN_logs/AGN_LX_table_2.log &
python AGN_setup.py 3   #> AGN_logs/AGN_LX_table_3.log &
python AGN_setup.py 4   #> AGN_logs/AGN_LX_table_4.log &
python AGN_setup.py 5   #> AGN_logs/AGN_LX_table_5.log &
python AGN_setup.py 6   #> AGN_logs/AGN_LX_table_6.log &
python AGN_setup.py 7   #> AGN_logs/AGN_LX_table_7.log &
python AGN_setup.py 8   #> AGN_logs/AGN_LX_table_8.log &
python AGN_setup.py 9   #> AGN_logs/AGN_LX_table_9.log &
python AGN_setup.py 10  #> AGN_logs/AGN_LX_table_10.log &
python AGN_setup.py 11  #> AGN_logs/AGN_LX_table_11.log &
python AGN_setup.py 12  #> AGN_logs/AGN_LX_table_12.log &
python AGN_setup.py 13  #> AGN_logs/AGN_LX_table_13.log &
python AGN_setup.py 14  #> AGN_logs/AGN_LX_table_14.log &
python AGN_setup.py 15  #> AGN_logs/AGN_LX_table_15.log &
python AGN_setup.py 16  #> AGN_logs/AGN_LX_table_16.log &
python AGN_setup.py 17  #> AGN_logs/AGN_LX_table_17.log &
python AGN_setup.py 18  #> AGN_logs/AGN_LX_table_18.log &
python AGN_setup.py 19  #> AGN_logs/AGN_LX_table_19.log &
python AGN_setup.py 20  #> AGN_logs/AGN_LX_table_20.log &
python AGN_setup.py 21  #> AGN_logs/AGN_LX_table_21.log &
python AGN_setup.py 22  #> AGN_logs/AGN_LX_table_22.log &
python AGN_setup.py 23  #> AGN_logs/AGN_LX_table_23.log &
python AGN_setup.py 24  #> AGN_logs/AGN_LX_table_24.log &
python AGN_setup.py 25  #> AGN_logs/AGN_LX_table_25.log &
python AGN_setup.py 26  #> AGN_logs/AGN_LX_table_26.log &
python AGN_setup.py 27  #> AGN_logs/AGN_LX_table_27.log &
python AGN_setup.py 28  #> AGN_logs/AGN_LX_table_28.log &
python AGN_setup.py 29  #> AGN_logs/AGN_LX_table_29.log &
python AGN_setup.py 30  #> AGN_logs/AGN_LX_table_30.log &
python AGN_setup.py 31  #> AGN_logs/AGN_LX_table_31.log &
python AGN_setup.py 32  #> AGN_logs/AGN_LX_table_32.log &
python AGN_setup.py 33  #> AGN_logs/AGN_LX_table_33.log &
python AGN_setup.py 34  #> AGN_logs/AGN_LX_table_34.log &
python AGN_setup.py 35  #> AGN_logs/AGN_LX_table_35.log &
python AGN_setup.py 36  #> AGN_logs/AGN_LX_table_36.log &
python AGN_setup.py 37  #> AGN_logs/AGN_LX_table_37.log &
python AGN_setup.py 38  #> AGN_logs/AGN_LX_table_38.log &
python AGN_setup.py 39  #> AGN_logs/AGN_LX_table_39.log &
python AGN_setup.py 40  #> AGN_logs/AGN_LX_table_40.log &
python AGN_setup.py 41  #> AGN_logs/AGN_LX_table_41.log &
python AGN_setup.py 42  #> AGN_logs/AGN_LX_table_42.log &
python AGN_setup.py 43  #> AGN_logs/AGN_LX_table_43.log &
python AGN_setup.py 44  #> AGN_logs/AGN_LX_table_44.log &
python AGN_setup.py 45  #> AGN_logs/AGN_LX_table_45.log &
python AGN_setup.py 46  #> AGN_logs/AGN_LX_table_46.log &
python AGN_setup.py 47  #> AGN_logs/AGN_LX_table_47.log &
python AGN_setup.py 48  #> AGN_logs/AGN_LX_table_48.log &
python AGN_setup.py 49  #> AGN_logs/AGN_LX_table_49.log &
python AGN_setup.py 50  #> AGN_logs/AGN_LX_table_50.log &
python AGN_setup.py 51  #> AGN_logs/AGN_LX_table_51.log &
python AGN_setup.py 52  #> AGN_logs/AGN_LX_table_52.log &
python AGN_setup.py 53  #> AGN_logs/AGN_LX_table_53.log &
python AGN_setup.py 54  #> AGN_logs/AGN_LX_table_54.log &
python AGN_setup.py 55  #> AGN_logs/AGN_LX_table_55.log &
python AGN_setup.py 56  #> AGN_logs/AGN_LX_table_56.log &
python AGN_setup.py 57  #> AGN_logs/AGN_LX_table_57.log &
python AGN_setup.py 58  #> AGN_logs/AGN_LX_table_58.log &
python AGN_setup.py 59  #> AGN_logs/AGN_LX_table_59.log &
python AGN_setup.py 60  #> AGN_logs/AGN_LX_table_60.log &
python AGN_setup.py 61  #> AGN_logs/AGN_LX_table_61.log &
python AGN_setup.py 62  #> AGN_logs/AGN_LX_table_62.log &
python AGN_setup.py 63  #> AGN_logs/AGN_LX_table_63.log &
python AGN_setup.py 64  #> AGN_logs/AGN_LX_table_64.log &
python AGN_setup.py 65  #> AGN_logs/AGN_LX_table_65.log &
python AGN_setup.py 66  #> AGN_logs/AGN_LX_table_66.log &
python AGN_setup.py 67  #> AGN_logs/AGN_LX_table_67.log &
python AGN_setup.py 68  #> AGN_logs/AGN_LX_table_68.log &
python AGN_setup.py 69  #> AGN_logs/AGN_LX_table_69.log &
python AGN_setup.py 70  #> AGN_logs/AGN_LX_table_70.log &
python AGN_setup.py 71  #> AGN_logs/AGN_LX_table_71.log &
python AGN_setup.py 72  #> AGN_logs/AGN_LX_table_72.log &
python AGN_setup.py 73  #> AGN_logs/AGN_LX_table_73.log &
python AGN_setup.py 74  #> AGN_logs/AGN_LX_table_74.log &
python AGN_setup.py 75  #> AGN_logs/AGN_LX_table_75.log &
python AGN_setup.py 76  #> AGN_logs/AGN_LX_table_76.log &
python AGN_setup.py 77  #> AGN_logs/AGN_LX_table_77.log &
python AGN_setup.py 78  #> AGN_logs/AGN_LX_table_78.log &
python AGN_setup.py 79  #> AGN_logs/AGN_LX_table_79.log &
python AGN_setup.py 80  #> AGN_logs/AGN_LX_table_80.log &
python AGN_setup.py 81  #> AGN_logs/AGN_LX_table_81.log &
python AGN_setup.py 82  #> AGN_logs/AGN_LX_table_82.log &
python AGN_setup.py 83  #> AGN_logs/AGN_LX_table_83.log &
python AGN_setup.py 84  #> AGN_logs/AGN_LX_table_84.log &
python AGN_setup.py 85  #> AGN_logs/AGN_LX_table_85.log &
python AGN_setup.py 86  #> AGN_logs/AGN_LX_table_86.log &
python AGN_setup.py 87  #> AGN_logs/AGN_LX_table_87.log &
python AGN_setup.py 88  #> AGN_logs/AGN_LX_table_88.log &
python AGN_setup.py 89  #> AGN_logs/AGN_LX_table_89.log &
python AGN_setup.py 90  #> AGN_logs/AGN_LX_table_90.log &
python AGN_setup.py 91  #> AGN_logs/AGN_LX_table_91.log &
python AGN_setup.py 92  #> AGN_logs/AGN_LX_table_92.log &
python AGN_setup.py 93  #> AGN_logs/AGN_LX_table_93.log &
python AGN_setup.py 94  #> AGN_logs/AGN_LX_table_94.log &
python AGN_setup.py 95  #> AGN_logs/AGN_LX_table_95.log &
python AGN_setup.py 96  #> AGN_logs/AGN_LX_table_96.log &
python AGN_setup.py 97  #> AGN_logs/AGN_LX_table_97.log &
python AGN_setup.py 98  #> AGN_logs/AGN_LX_table_98.log &
python AGN_setup.py 99  #> AGN_logs/AGN_LX_table_99.log &
python AGN_setup.py 100 #> AGN_logs/AGN_LX_table_100.log &
python AGN_setup.py 101 #> AGN_logs/AGN_LX_table_101.log &
python AGN_setup.py 102 #> AGN_logs/AGN_LX_table_102.log &
python AGN_setup.py 103 #> AGN_logs/AGN_LX_table_103.log &
python AGN_setup.py 104 #> AGN_logs/AGN_LX_table_104.log &
python AGN_setup.py 105 #> AGN_logs/AGN_LX_table_105.log &
python AGN_setup.py 106 #> AGN_logs/AGN_LX_table_106.log &
python AGN_setup.py 107 #> AGN_logs/AGN_LX_table_107.log &
python AGN_setup.py 108 #> AGN_logs/AGN_LX_table_108.log &
python AGN_setup.py 109 #> AGN_logs/AGN_LX_table_109.log &
python AGN_setup.py 110 #> AGN_logs/AGN_LX_table_110.log &
python AGN_setup.py 111 #> AGN_logs/AGN_LX_table_111.log &
python AGN_setup.py 112 #> AGN_logs/AGN_LX_table_112.log &
python AGN_setup.py 113 #> AGN_logs/AGN_LX_table_113.log &
python AGN_setup.py 114 #> AGN_logs/AGN_LX_table_114.log &
python AGN_setup.py 115 #> AGN_logs/AGN_LX_table_115.log &
python AGN_setup.py 116 #> AGN_logs/AGN_LX_table_116.log &
python AGN_setup.py 117 #> AGN_logs/AGN_LX_table_117.log &
python AGN_setup.py 118 #> AGN_logs/AGN_LX_table_118.log &
python AGN_setup.py 119 #> AGN_logs/AGN_LX_table_119.log &
python AGN_setup.py 120 #> AGN_logs/AGN_LX_table_120.log &
python AGN_setup.py 121 #> AGN_logs/AGN_LX_table_121.log &
python AGN_setup.py 122 #> AGN_logs/AGN_LX_table_122.log &
python AGN_setup.py 123 #> AGN_logs/AGN_LX_table_123.log &
python AGN_setup.py 124 #> AGN_logs/AGN_LX_table_124.log &
python AGN_setup.py 125 #> AGN_logs/AGN_LX_table_125.log &
python AGN_setup.py 126 #> AGN_logs/AGN_LX_table_126.log &
python AGN_setup.py 127 #> AGN_logs/AGN_LX_table_127.log &
python AGN_setup.py 128 #> AGN_logs/AGN_LX_table_128.log &
python AGN_setup.py 129 #> AGN_logs/AGN_LX_table_129.log &
python AGN_setup.py 130 #> AGN_logs/AGN_LX_table_130.log &
python AGN_setup.py 131 #> AGN_logs/AGN_LX_table_131.log &
python AGN_setup.py 132 #> AGN_logs/AGN_LX_table_132.log &
python AGN_setup.py 133 #> AGN_logs/AGN_LX_table_133.log &
python AGN_setup.py 134 #> AGN_logs/AGN_LX_table_134.log &
python AGN_setup.py 135 #> AGN_logs/AGN_LX_table_135.log &
python AGN_setup.py 136 #> AGN_logs/AGN_LX_table_136.log &
python AGN_setup.py 137 #> AGN_logs/AGN_LX_table_137.log &
python AGN_setup.py 138 #> AGN_logs/AGN_LX_table_138.log &
python AGN_setup.py 139 #> AGN_logs/AGN_LX_table_139.log &
python AGN_setup.py 140 #> AGN_logs/AGN_LX_table_140.log &
python AGN_setup.py 141 #> AGN_logs/AGN_LX_table_141.log &
python AGN_setup.py 142 #> AGN_logs/AGN_LX_table_142.log &
python AGN_setup.py 143 #> AGN_logs/AGN_LX_table_143.log &
python AGN_setup.py 144 #> AGN_logs/AGN_LX_table_144.log &
python AGN_setup.py 145 #> AGN_logs/AGN_LX_table_145.log &
python AGN_setup.py 146 #> AGN_logs/AGN_LX_table_146.log &
python AGN_setup.py 147 #> AGN_logs/AGN_LX_table_147.log &
python AGN_setup.py 148 #> AGN_logs/AGN_LX_table_148.log &
python AGN_setup.py 149 #> AGN_logs/AGN_LX_table_149.log &
python AGN_setup.py 150 #> AGN_logs/AGN_LX_table_150.log &
python AGN_setup.py 151 #> AGN_logs/AGN_LX_table_151.log &
python AGN_setup.py 152 #> AGN_logs/AGN_LX_table_152.log &
python AGN_setup.py 153 #> AGN_logs/AGN_LX_table_153.log &
python AGN_setup.py 154 #> AGN_logs/AGN_LX_table_154.log &
python AGN_setup.py 155 #> AGN_logs/AGN_LX_table_155.log &
python AGN_setup.py 156 #> AGN_logs/AGN_LX_table_156.log &
python AGN_setup.py 157 #> AGN_logs/AGN_LX_table_157.log &
python AGN_setup.py 158 #> AGN_logs/AGN_LX_table_158.log &
python AGN_setup.py 159 #> AGN_logs/AGN_LX_table_159.log &
python AGN_setup.py 160 #> AGN_logs/AGN_LX_table_160.log &
python AGN_setup.py 161 #> AGN_logs/AGN_LX_table_161.log &
python AGN_setup.py 162 #> AGN_logs/AGN_LX_table_162.log &
python AGN_setup.py 163 #> AGN_logs/AGN_LX_table_163.log &
python AGN_setup.py 164 #> AGN_logs/AGN_LX_table_164.log &
python AGN_setup.py 165 #> AGN_logs/AGN_LX_table_165.log &
python AGN_setup.py 166 #> AGN_logs/AGN_LX_table_166.log &
python AGN_setup.py 167 #> AGN_logs/AGN_LX_table_167.log &
python AGN_setup.py 168 #> AGN_logs/AGN_LX_table_168.log &
python AGN_setup.py 169 #> AGN_logs/AGN_LX_table_169.log &
python AGN_setup.py 170 #> AGN_logs/AGN_LX_table_170.log &
python AGN_setup.py 171 #> AGN_logs/AGN_LX_table_171.log &
python AGN_setup.py 172 #> AGN_logs/AGN_LX_table_172.log &
python AGN_setup.py 173 #> AGN_logs/AGN_LX_table_173.log &
python AGN_setup.py 174 #> AGN_logs/AGN_LX_table_174.log &
python AGN_setup.py 175 #> AGN_logs/AGN_LX_table_175.log &
python AGN_setup.py 176 #> AGN_logs/AGN_LX_table_176.log &
python AGN_setup.py 177 #> AGN_logs/AGN_LX_table_177.log &
python AGN_setup.py 178 #> AGN_logs/AGN_LX_table_178.log &
python AGN_setup.py 179 #> AGN_logs/AGN_LX_table_179.log &
python AGN_setup.py 180 #> AGN_logs/AGN_LX_table_180.log &
python AGN_setup.py 181 #> AGN_logs/AGN_LX_table_181.log &
python AGN_setup.py 182 #> AGN_logs/AGN_LX_table_182.log &
python AGN_setup.py 183 #> AGN_logs/AGN_LX_table_183.log &
python AGN_setup.py 184 #> AGN_logs/AGN_LX_table_184.log &
python AGN_setup.py 185 #> AGN_logs/AGN_LX_table_185.log &
python AGN_setup.py 186 #> AGN_logs/AGN_LX_table_186.log &
python AGN_setup.py 187 #> AGN_logs/AGN_LX_table_187.log &
python AGN_setup.py 188 #> AGN_logs/AGN_LX_table_188.log &
python AGN_setup.py 189 #> AGN_logs/AGN_LX_table_189.log &
python AGN_setup.py 190 #> AGN_logs/AGN_LX_table_190.log &
python AGN_setup.py 191 #> AGN_logs/AGN_LX_table_191.log &
python AGN_setup.py 192 #> AGN_logs/AGN_LX_table_192.log &
python AGN_setup.py 193 #> AGN_logs/AGN_LX_table_193.log &
python AGN_setup.py 194 #> AGN_logs/AGN_LX_table_194.log &
python AGN_setup.py 195 #> AGN_logs/AGN_LX_table_195.log &
python AGN_setup.py 196 #> AGN_logs/AGN_LX_table_196.log &
python AGN_setup.py 197 #> AGN_logs/AGN_LX_table_197.log &
python AGN_setup.py 198 #> AGN_logs/AGN_LX_table_198.log &
python AGN_setup.py 199 #> AGN_logs/AGN_LX_table_199.log &
python AGN_setup.py 200 #> AGN_logs/AGN_LX_table_200.log &
python AGN_setup.py 201 #> AGN_logs/AGN_LX_table_201.log &
python AGN_setup.py 202 #> AGN_logs/AGN_LX_table_202.log &
python AGN_setup.py 203 #> AGN_logs/AGN_LX_table_203.log &
python AGN_setup.py 204 #> AGN_logs/AGN_LX_table_204.log &
python AGN_setup.py 205 #> AGN_logs/AGN_LX_table_205.log &
python AGN_setup.py 206 #> AGN_logs/AGN_LX_table_206.log &
python AGN_setup.py 207 #> AGN_logs/AGN_LX_table_207.log &
python AGN_setup.py 208 #> AGN_logs/AGN_LX_table_208.log &
python AGN_setup.py 209 #> AGN_logs/AGN_LX_table_209.log &
python AGN_setup.py 210 #> AGN_logs/AGN_LX_table_210.log &
python AGN_setup.py 211 #> AGN_logs/AGN_LX_table_211.log &
python AGN_setup.py 212 #> AGN_logs/AGN_LX_table_212.log &
python AGN_setup.py 213 #> AGN_logs/AGN_LX_table_213.log &
python AGN_setup.py 214 #> AGN_logs/AGN_LX_table_214.log &
python AGN_setup.py 215 #> AGN_logs/AGN_LX_table_215.log &
python AGN_setup.py 216 #> AGN_logs/AGN_LX_table_216.log &
python AGN_setup.py 217 #> AGN_logs/AGN_LX_table_217.log &
python AGN_setup.py 218 #> AGN_logs/AGN_LX_table_218.log &
python AGN_setup.py 219 #> AGN_logs/AGN_LX_table_219.log &
python AGN_setup.py 220 #> AGN_logs/AGN_LX_table_220.log &
python AGN_setup.py 221 #> AGN_logs/AGN_LX_table_221.log &
python AGN_setup.py 222 #> AGN_logs/AGN_LX_table_222.log &
python AGN_setup.py 223 #> AGN_logs/AGN_LX_table_223.log &
python AGN_setup.py 224 #> AGN_logs/AGN_LX_table_224.log &
python AGN_setup.py 225 #> AGN_logs/AGN_LX_table_225.log &
python AGN_setup.py 226 #> AGN_logs/AGN_LX_table_226.log &
python AGN_setup.py 227 #> AGN_logs/AGN_LX_table_227.log &
python AGN_setup.py 228 #> AGN_logs/AGN_LX_table_228.log &
python AGN_setup.py 229 #> AGN_logs/AGN_LX_table_229.log &
python AGN_setup.py 230 #> AGN_logs/AGN_LX_table_230.log &
python AGN_setup.py 231 #> AGN_logs/AGN_LX_table_231.log &
python AGN_setup.py 232 #> AGN_logs/AGN_LX_table_232.log &
python AGN_setup.py 233 #> AGN_logs/AGN_LX_table_233.log &
python AGN_setup.py 234 #> AGN_logs/AGN_LX_table_234.log &
python AGN_setup.py 235 #> AGN_logs/AGN_LX_table_235.log &
python AGN_setup.py 236 #> AGN_logs/AGN_LX_table_236.log &
python AGN_setup.py 237 #> AGN_logs/AGN_LX_table_237.log &
python AGN_setup.py 238 #> AGN_logs/AGN_LX_table_238.log &
python AGN_setup.py 239 #> AGN_logs/AGN_LX_table_239.log &
python AGN_setup.py 240 #> AGN_logs/AGN_LX_table_240.log &
python AGN_setup.py 241 #> AGN_logs/AGN_LX_table_241.log &
python AGN_setup.py 242 #> AGN_logs/AGN_LX_table_242.log &
python AGN_setup.py 243 #> AGN_logs/AGN_LX_table_243.log &
python AGN_setup.py 244 #> AGN_logs/AGN_LX_table_244.log &
python AGN_setup.py 245 #> AGN_logs/AGN_LX_table_245.log &
python AGN_setup.py 246 #> AGN_logs/AGN_LX_table_246.log &
python AGN_setup.py 247 #> AGN_logs/AGN_LX_table_247.log &
python AGN_setup.py 248 #> AGN_logs/AGN_LX_table_248.log &
python AGN_setup.py 249 #> AGN_logs/AGN_LX_table_249.log &
python AGN_setup.py 250 #> AGN_logs/AGN_LX_table_250.log &
python AGN_setup.py 251 #> AGN_logs/AGN_LX_table_251.log &
python AGN_setup.py 252 #> AGN_logs/AGN_LX_table_252.log &
python AGN_setup.py 253 #> AGN_logs/AGN_LX_table_253.log &
python AGN_setup.py 254 #> AGN_logs/AGN_LX_table_254.log &
python AGN_setup.py 255 #> AGN_logs/AGN_LX_table_255.log &
python AGN_setup.py 256 #> AGN_logs/AGN_LX_table_256.log &
python AGN_setup.py 257 #> AGN_logs/AGN_LX_table_257.log &
python AGN_setup.py 258 #> AGN_logs/AGN_LX_table_258.log &
python AGN_setup.py 259 #> AGN_logs/AGN_LX_table_259.log &
python AGN_setup.py 260 #> AGN_logs/AGN_LX_table_260.log &
python AGN_setup.py 261 #> AGN_logs/AGN_LX_table_261.log &
python AGN_setup.py 262 #> AGN_logs/AGN_LX_table_262.log &
python AGN_setup.py 263 #> AGN_logs/AGN_LX_table_263.log &
python AGN_setup.py 264 #> AGN_logs/AGN_LX_table_264.log &
python AGN_setup.py 265 #> AGN_logs/AGN_LX_table_265.log &
python AGN_setup.py 266 #> AGN_logs/AGN_LX_table_266.log &
python AGN_setup.py 267 #> AGN_logs/AGN_LX_table_267.log &
python AGN_setup.py 268 #> AGN_logs/AGN_LX_table_268.log &
python AGN_setup.py 269 #> AGN_logs/AGN_LX_table_269.log &
python AGN_setup.py 270 #> AGN_logs/AGN_LX_table_270.log &
python AGN_setup.py 271 #> AGN_logs/AGN_LX_table_271.log &
python AGN_setup.py 272 #> AGN_logs/AGN_LX_table_272.log &
python AGN_setup.py 273 #> AGN_logs/AGN_LX_table_273.log &
python AGN_setup.py 274 #> AGN_logs/AGN_LX_table_274.log &
python AGN_setup.py 275 #> AGN_logs/AGN_LX_table_275.log &
python AGN_setup.py 276 #> AGN_logs/AGN_LX_table_276.log &
python AGN_setup.py 277 #> AGN_logs/AGN_LX_table_277.log &
python AGN_setup.py 278 #> AGN_logs/AGN_LX_table_278.log &
python AGN_setup.py 279 #> AGN_logs/AGN_LX_table_279.log &
python AGN_setup.py 280 #> AGN_logs/AGN_LX_table_280.log &
python AGN_setup.py 281 #> AGN_logs/AGN_LX_table_281.log &
python AGN_setup.py 282 #> AGN_logs/AGN_LX_table_282.log &
python AGN_setup.py 283 #> AGN_logs/AGN_LX_table_283.log &
python AGN_setup.py 284 #> AGN_logs/AGN_LX_table_284.log &
python AGN_setup.py 285 #> AGN_logs/AGN_LX_table_285.log &
python AGN_setup.py 286 #> AGN_logs/AGN_LX_table_286.log &
python AGN_setup.py 287 #> AGN_logs/AGN_LX_table_287.log &
python AGN_setup.py 288 #> AGN_logs/AGN_LX_table_288.log &
python AGN_setup.py 289 #> AGN_logs/AGN_LX_table_289.log &
python AGN_setup.py 290 #> AGN_logs/AGN_LX_table_290.log &
python AGN_setup.py 291 #> AGN_logs/AGN_LX_table_291.log &
python AGN_setup.py 292 #> AGN_logs/AGN_LX_table_292.log &
python AGN_setup.py 293 #> AGN_logs/AGN_LX_table_293.log &
python AGN_setup.py 294 #> AGN_logs/AGN_LX_table_294.log &
python AGN_setup.py 295 #> AGN_logs/AGN_LX_table_295.log &
python AGN_setup.py 296 #> AGN_logs/AGN_LX_table_296.log &
python AGN_setup.py 297 #> AGN_logs/AGN_LX_table_297.log &
python AGN_setup.py 298 #> AGN_logs/AGN_LX_table_298.log &
python AGN_setup.py 299 #> AGN_logs/AGN_LX_table_299.log &
python AGN_setup.py 300 #> AGN_logs/AGN_LX_table_300.log &
python AGN_setup.py 301 #> AGN_logs/AGN_LX_table_301.log &
python AGN_setup.py 302 #> AGN_logs/AGN_LX_table_302.log &
python AGN_setup.py 303 #> AGN_logs/AGN_LX_table_303.log &
python AGN_setup.py 304 #> AGN_logs/AGN_LX_table_304.log &
python AGN_setup.py 305 #> AGN_logs/AGN_LX_table_305.log &
python AGN_setup.py 306 #> AGN_logs/AGN_LX_table_306.log &
python AGN_setup.py 307 #> AGN_logs/AGN_LX_table_307.log &
python AGN_setup.py 308 #> AGN_logs/AGN_LX_table_308.log &
python AGN_setup.py 309 #> AGN_logs/AGN_LX_table_309.log &
python AGN_setup.py 310 #> AGN_logs/AGN_LX_table_310.log &
python AGN_setup.py 311 #> AGN_logs/AGN_LX_table_311.log &
python AGN_setup.py 312 #> AGN_logs/AGN_LX_table_312.log &
python AGN_setup.py 313 #> AGN_logs/AGN_LX_table_313.log &
python AGN_setup.py 314 #> AGN_logs/AGN_LX_table_314.log &
python AGN_setup.py 315 #> AGN_logs/AGN_LX_table_315.log &
python AGN_setup.py 316 #> AGN_logs/AGN_LX_table_316.log &
python AGN_setup.py 317 #> AGN_logs/AGN_LX_table_317.log &
python AGN_setup.py 318 #> AGN_logs/AGN_LX_table_318.log &
python AGN_setup.py 319 #> AGN_logs/AGN_LX_table_319.log &
python AGN_setup.py 320 #> AGN_logs/AGN_LX_table_320.log &
python AGN_setup.py 321 #> AGN_logs/AGN_LX_table_321.log &
python AGN_setup.py 322 #> AGN_logs/AGN_LX_table_322.log &
python AGN_setup.py 323 #> AGN_logs/AGN_LX_table_323.log &
python AGN_setup.py 324 #> AGN_logs/AGN_LX_table_324.log &
python AGN_setup.py 325 #> AGN_logs/AGN_LX_table_325.log &
python AGN_setup.py 326 #> AGN_logs/AGN_LX_table_326.log &
python AGN_setup.py 327 #> AGN_logs/AGN_LX_table_327.log &
python AGN_setup.py 328 #> AGN_logs/AGN_LX_table_328.log &
python AGN_setup.py 329 #> AGN_logs/AGN_LX_table_329.log &
python AGN_setup.py 330 #> AGN_logs/AGN_LX_table_330.log &
python AGN_setup.py 331 #> AGN_logs/AGN_LX_table_331.log &
python AGN_setup.py 332 #> AGN_logs/AGN_LX_table_332.log &
python AGN_setup.py 333 #> AGN_logs/AGN_LX_table_333.log &
python AGN_setup.py 334 #> AGN_logs/AGN_LX_table_334.log &
python AGN_setup.py 335 #> AGN_logs/AGN_LX_table_335.log &
python AGN_setup.py 336 #> AGN_logs/AGN_LX_table_336.log &
python AGN_setup.py 337 #> AGN_logs/AGN_LX_table_337.log &
python AGN_setup.py 338 #> AGN_logs/AGN_LX_table_338.log &
python AGN_setup.py 339 #> AGN_logs/AGN_LX_table_339.log &
python AGN_setup.py 340 #> AGN_logs/AGN_LX_table_340.log &
python AGN_setup.py 341 #> AGN_logs/AGN_LX_table_341.log &
python AGN_setup.py 342 #> AGN_logs/AGN_LX_table_342.log &
python AGN_setup.py 343 #> AGN_logs/AGN_LX_table_343.log &
python AGN_setup.py 344 #> AGN_logs/AGN_LX_table_344.log &
python AGN_setup.py 345 #> AGN_logs/AGN_LX_table_345.log &
python AGN_setup.py 346 #> AGN_logs/AGN_LX_table_346.log &
python AGN_setup.py 347 #> AGN_logs/AGN_LX_table_347.log &
python AGN_setup.py 348 #> AGN_logs/AGN_LX_table_348.log &
python AGN_setup.py 349 #> AGN_logs/AGN_LX_table_349.log &
python AGN_setup.py 350 #> AGN_logs/AGN_LX_table_350.log &
python AGN_setup.py 351 #> AGN_logs/AGN_LX_table_351.log &
python AGN_setup.py 352 #> AGN_logs/AGN_LX_table_352.log &
python AGN_setup.py 353 #> AGN_logs/AGN_LX_table_353.log &
python AGN_setup.py 354 #> AGN_logs/AGN_LX_table_354.log &
python AGN_setup.py 355 #> AGN_logs/AGN_LX_table_355.log &
python AGN_setup.py 356 #> AGN_logs/AGN_LX_table_356.log &
python AGN_setup.py 357 #> AGN_logs/AGN_LX_table_357.log &
python AGN_setup.py 358 #> AGN_logs/AGN_LX_table_358.log &
python AGN_setup.py 359 #> AGN_logs/AGN_LX_table_359.log &
python AGN_setup.py 360 #> AGN_logs/AGN_LX_table_360.log &
python AGN_setup.py 361 #> AGN_logs/AGN_LX_table_361.log &
python AGN_setup.py 362 #> AGN_logs/AGN_LX_table_362.log &
python AGN_setup.py 363 #> AGN_logs/AGN_LX_table_363.log &
python AGN_setup.py 364 #> AGN_logs/AGN_LX_table_364.log &
python AGN_setup.py 365 #> AGN_logs/AGN_LX_table_365.log &
python AGN_setup.py 366 #> AGN_logs/AGN_LX_table_366.log &
python AGN_setup.py 367 #> AGN_logs/AGN_LX_table_367.log &
python AGN_setup.py 368 #> AGN_logs/AGN_LX_table_368.log &
python AGN_setup.py 369 #> AGN_logs/AGN_LX_table_369.log &
python AGN_setup.py 370 #> AGN_logs/AGN_LX_table_370.log &
python AGN_setup.py 371 #> AGN_logs/AGN_LX_table_371.log &
python AGN_setup.py 372 #> AGN_logs/AGN_LX_table_372.log &
python AGN_setup.py 373 #> AGN_logs/AGN_LX_table_373.log &
python AGN_setup.py 374 #> AGN_logs/AGN_LX_table_374.log &
python AGN_setup.py 375 #> AGN_logs/AGN_LX_table_375.log &
python AGN_setup.py 376 #> AGN_logs/AGN_LX_table_376.log &
python AGN_setup.py 377 #> AGN_logs/AGN_LX_table_377.log &
python AGN_setup.py 378 #> AGN_logs/AGN_LX_table_378.log &
python AGN_setup.py 379 #> AGN_logs/AGN_LX_table_379.log &
python AGN_setup.py 380 #> AGN_logs/AGN_LX_table_380.log &
python AGN_setup.py 381 #> AGN_logs/AGN_LX_table_381.log &
python AGN_setup.py 382 #> AGN_logs/AGN_LX_table_382.log &
python AGN_setup.py 383 #> AGN_logs/AGN_LX_table_383.log &
python AGN_setup.py 384 #> AGN_logs/AGN_LX_table_384.log &
python AGN_setup.py 385 #> AGN_logs/AGN_LX_table_385.log &
python AGN_setup.py 386 #> AGN_logs/AGN_LX_table_386.log &
python AGN_setup.py 387 #> AGN_logs/AGN_LX_table_387.log &
python AGN_setup.py 388 #> AGN_logs/AGN_LX_table_388.log &
python AGN_setup.py 389 #> AGN_logs/AGN_LX_table_389.log &
python AGN_setup.py 390 #> AGN_logs/AGN_LX_table_390.log &
python AGN_setup.py 391 #> AGN_logs/AGN_LX_table_391.log &
python AGN_setup.py 392 #> AGN_logs/AGN_LX_table_392.log &
python AGN_setup.py 393 #> AGN_logs/AGN_LX_table_393.log &
python AGN_setup.py 394 #> AGN_logs/AGN_LX_table_394.log &
python AGN_setup.py 395 #> AGN_logs/AGN_LX_table_395.log &
python AGN_setup.py 396 #> AGN_logs/AGN_LX_table_396.log &
python AGN_setup.py 397 #> AGN_logs/AGN_LX_table_397.log &
python AGN_setup.py 398 #> AGN_logs/AGN_LX_table_398.log &
python AGN_setup.py 399 #> AGN_logs/AGN_LX_table_399.log &
python AGN_setup.py 400 #> AGN_logs/AGN_LX_table_400.log &
python AGN_setup.py 401 #> AGN_logs/AGN_LX_table_401.log &
python AGN_setup.py 402 #> AGN_logs/AGN_LX_table_402.log &
python AGN_setup.py 403 #> AGN_logs/AGN_LX_table_403.log &
python AGN_setup.py 404 #> AGN_logs/AGN_LX_table_404.log &
python AGN_setup.py 405 #> AGN_logs/AGN_LX_table_405.log &
python AGN_setup.py 406 #> AGN_logs/AGN_LX_table_406.log &
python AGN_setup.py 407 #> AGN_logs/AGN_LX_table_407.log &
python AGN_setup.py 408 #> AGN_logs/AGN_LX_table_408.log &
python AGN_setup.py 409 #> AGN_logs/AGN_LX_table_409.log &
python AGN_setup.py 410 #> AGN_logs/AGN_LX_table_410.log &
python AGN_setup.py 411 #> AGN_logs/AGN_LX_table_411.log &
python AGN_setup.py 412 #> AGN_logs/AGN_LX_table_412.log &
python AGN_setup.py 413 #> AGN_logs/AGN_LX_table_413.log &
python AGN_setup.py 414 #> AGN_logs/AGN_LX_table_414.log &
python AGN_setup.py 415 #> AGN_logs/AGN_LX_table_415.log &
python AGN_setup.py 416 #> AGN_logs/AGN_LX_table_416.log &
python AGN_setup.py 417 #> AGN_logs/AGN_LX_table_417.log &
python AGN_setup.py 418 #> AGN_logs/AGN_LX_table_418.log &
python AGN_setup.py 419 #> AGN_logs/AGN_LX_table_419.log &
python AGN_setup.py 420 #> AGN_logs/AGN_LX_table_420.log &
python AGN_setup.py 421 #> AGN_logs/AGN_LX_table_421.log &
python AGN_setup.py 422 #> AGN_logs/AGN_LX_table_422.log &
python AGN_setup.py 423 #> AGN_logs/AGN_LX_table_423.log &
python AGN_setup.py 424 #> AGN_logs/AGN_LX_table_424.log &
python AGN_setup.py 425 #> AGN_logs/AGN_LX_table_425.log &
python AGN_setup.py 426 #> AGN_logs/AGN_LX_table_426.log &
python AGN_setup.py 427 #> AGN_logs/AGN_LX_table_427.log &
python AGN_setup.py 428 #> AGN_logs/AGN_LX_table_428.log &
python AGN_setup.py 429 #> AGN_logs/AGN_LX_table_429.log &
python AGN_setup.py 430 #> AGN_logs/AGN_LX_table_430.log &
python AGN_setup.py 431 #> AGN_logs/AGN_LX_table_431.log &
python AGN_setup.py 432 #> AGN_logs/AGN_LX_table_432.log &
python AGN_setup.py 433 #> AGN_logs/AGN_LX_table_433.log &
python AGN_setup.py 434 #> AGN_logs/AGN_LX_table_434.log &
python AGN_setup.py 435 #> AGN_logs/AGN_LX_table_435.log &
python AGN_setup.py 436 #> AGN_logs/AGN_LX_table_436.log &
python AGN_setup.py 437 #> AGN_logs/AGN_LX_table_437.log &
python AGN_setup.py 438 #> AGN_logs/AGN_LX_table_438.log &
python AGN_setup.py 439 #> AGN_logs/AGN_LX_table_439.log &
python AGN_setup.py 440 #> AGN_logs/AGN_LX_table_440.log &
python AGN_setup.py 441 #> AGN_logs/AGN_LX_table_441.log &
python AGN_setup.py 442 #> AGN_logs/AGN_LX_table_442.log &
python AGN_setup.py 443 #> AGN_logs/AGN_LX_table_443.log &
python AGN_setup.py 444 #> AGN_logs/AGN_LX_table_444.log &
python AGN_setup.py 445 #> AGN_logs/AGN_LX_table_445.log &
python AGN_setup.py 446 #> AGN_logs/AGN_LX_table_446.log &
python AGN_setup.py 447 #> AGN_logs/AGN_LX_table_447.log &
python AGN_setup.py 448 #> AGN_logs/AGN_LX_table_448.log &
python AGN_setup.py 449 #> AGN_logs/AGN_LX_table_449.log &
python AGN_setup.py 450 #> AGN_logs/AGN_LX_table_450.log &
python AGN_setup.py 451 #> AGN_logs/AGN_LX_table_451.log &
python AGN_setup.py 452 #> AGN_logs/AGN_LX_table_452.log &
python AGN_setup.py 453 #> AGN_logs/AGN_LX_table_453.log &
python AGN_setup.py 454 #> AGN_logs/AGN_LX_table_454.log &
python AGN_setup.py 455 #> AGN_logs/AGN_LX_table_455.log &
python AGN_setup.py 456 #> AGN_logs/AGN_LX_table_456.log &
python AGN_setup.py 457 #> AGN_logs/AGN_LX_table_457.log &
python AGN_setup.py 458 #> AGN_logs/AGN_LX_table_458.log &
python AGN_setup.py 459 #> AGN_logs/AGN_LX_table_459.log &
python AGN_setup.py 460 #> AGN_logs/AGN_LX_table_460.log &
python AGN_setup.py 461 #> AGN_logs/AGN_LX_table_461.log &
python AGN_setup.py 462 #> AGN_logs/AGN_LX_table_462.log &
python AGN_setup.py 463 #> AGN_logs/AGN_LX_table_463.log &
python AGN_setup.py 464 #> AGN_logs/AGN_LX_table_464.log &
python AGN_setup.py 465 #> AGN_logs/AGN_LX_table_465.log &
python AGN_setup.py 466 #> AGN_logs/AGN_LX_table_466.log &
python AGN_setup.py 467 #> AGN_logs/AGN_LX_table_467.log &
python AGN_setup.py 468 #> AGN_logs/AGN_LX_table_468.log &
python AGN_setup.py 469 #> AGN_logs/AGN_LX_table_469.log &
python AGN_setup.py 470 #> AGN_logs/AGN_LX_table_470.log &
python AGN_setup.py 471 #> AGN_logs/AGN_LX_table_471.log &
python AGN_setup.py 472 #> AGN_logs/AGN_LX_table_472.log &
python AGN_setup.py 473 #> AGN_logs/AGN_LX_table_473.log &
python AGN_setup.py 474 #> AGN_logs/AGN_LX_table_474.log &
python AGN_setup.py 475 #> AGN_logs/AGN_LX_table_475.log &
python AGN_setup.py 476 #> AGN_logs/AGN_LX_table_476.log &
python AGN_setup.py 477 #> AGN_logs/AGN_LX_table_477.log &
python AGN_setup.py 478 #> AGN_logs/AGN_LX_table_478.log &
python AGN_setup.py 479 #> AGN_logs/AGN_LX_table_479.log &
python AGN_setup.py 480 #> AGN_logs/AGN_LX_table_480.log &
python AGN_setup.py 481 #> AGN_logs/AGN_LX_table_481.log &
python AGN_setup.py 482 #> AGN_logs/AGN_LX_table_482.log &
python AGN_setup.py 483 #> AGN_logs/AGN_LX_table_483.log &
python AGN_setup.py 484 #> AGN_logs/AGN_LX_table_484.log &
python AGN_setup.py 485 #> AGN_logs/AGN_LX_table_485.log &
python AGN_setup.py 486 #> AGN_logs/AGN_LX_table_486.log &
python AGN_setup.py 487 #> AGN_logs/AGN_LX_table_487.log &
python AGN_setup.py 488 #> AGN_logs/AGN_LX_table_488.log &
python AGN_setup.py 489 #> AGN_logs/AGN_LX_table_489.log &
python AGN_setup.py 490 #> AGN_logs/AGN_LX_table_490.log &
python AGN_setup.py 491 #> AGN_logs/AGN_LX_table_491.log &
python AGN_setup.py 492 #> AGN_logs/AGN_LX_table_492.log &
python AGN_setup.py 493 #> AGN_logs/AGN_LX_table_493.log &
python AGN_setup.py 494 #> AGN_logs/AGN_LX_table_494.log &
python AGN_setup.py 495 #> AGN_logs/AGN_LX_table_495.log &
python AGN_setup.py 496 #> AGN_logs/AGN_LX_table_496.log &
python AGN_setup.py 497 #> AGN_logs/AGN_LX_table_497.log &
python AGN_setup.py 498 #> AGN_logs/AGN_LX_table_498.log &
python AGN_setup.py 499 #> AGN_logs/AGN_LX_table_499.log &
python AGN_setup.py 500 #> AGN_logs/AGN_LX_table_500.log &
python AGN_setup.py 501 #> AGN_logs/AGN_LX_table_501.log &
python AGN_setup.py 502 #> AGN_logs/AGN_LX_table_502.log &
python AGN_setup.py 503 #> AGN_logs/AGN_LX_table_503.log &
python AGN_setup.py 504 #> AGN_logs/AGN_LX_table_504.log &
python AGN_setup.py 505 #> AGN_logs/AGN_LX_table_505.log &
python AGN_setup.py 506 #> AGN_logs/AGN_LX_table_506.log &
python AGN_setup.py 507 #> AGN_logs/AGN_LX_table_507.log &
python AGN_setup.py 508 #> AGN_logs/AGN_LX_table_508.log &
python AGN_setup.py 509 #> AGN_logs/AGN_LX_table_509.log &
python AGN_setup.py 510 #> AGN_logs/AGN_LX_table_510.log &
python AGN_setup.py 511 #> AGN_logs/AGN_LX_table_511.log &
python AGN_setup.py 512 #> AGN_logs/AGN_LX_table_512.log &
python AGN_setup.py 513 #> AGN_logs/AGN_LX_table_513.log &
python AGN_setup.py 514 #> AGN_logs/AGN_LX_table_514.log &
python AGN_setup.py 515 #> AGN_logs/AGN_LX_table_515.log &
python AGN_setup.py 516 #> AGN_logs/AGN_LX_table_516.log &
python AGN_setup.py 517 #> AGN_logs/AGN_LX_table_517.log &
python AGN_setup.py 518 #> AGN_logs/AGN_LX_table_518.log &
python AGN_setup.py 519 #> AGN_logs/AGN_LX_table_519.log &
python AGN_setup.py 520 #> AGN_logs/AGN_LX_table_520.log &
python AGN_setup.py 521 #> AGN_logs/AGN_LX_table_521.log &
python AGN_setup.py 522 #> AGN_logs/AGN_LX_table_522.log &
python AGN_setup.py 523 #> AGN_logs/AGN_LX_table_523.log &
python AGN_setup.py 524 #> AGN_logs/AGN_LX_table_524.log &
python AGN_setup.py 525 #> AGN_logs/AGN_LX_table_525.log &
python AGN_setup.py 526 #> AGN_logs/AGN_LX_table_526.log &
python AGN_setup.py 527 #> AGN_logs/AGN_LX_table_527.log &
python AGN_setup.py 528 #> AGN_logs/AGN_LX_table_528.log &
python AGN_setup.py 529 #> AGN_logs/AGN_LX_table_529.log &
python AGN_setup.py 530 #> AGN_logs/AGN_LX_table_530.log &
python AGN_setup.py 531 #> AGN_logs/AGN_LX_table_531.log &
python AGN_setup.py 532 #> AGN_logs/AGN_LX_table_532.log &
python AGN_setup.py 533 #> AGN_logs/AGN_LX_table_533.log &
python AGN_setup.py 534 #> AGN_logs/AGN_LX_table_534.log &
python AGN_setup.py 535 #> AGN_logs/AGN_LX_table_535.log &
python AGN_setup.py 536 #> AGN_logs/AGN_LX_table_536.log &
python AGN_setup.py 537 #> AGN_logs/AGN_LX_table_537.log &
python AGN_setup.py 538 #> AGN_logs/AGN_LX_table_538.log &
python AGN_setup.py 539 #> AGN_logs/AGN_LX_table_539.log &
python AGN_setup.py 540 #> AGN_logs/AGN_LX_table_540.log &
python AGN_setup.py 541 #> AGN_logs/AGN_LX_table_541.log &
python AGN_setup.py 542 #> AGN_logs/AGN_LX_table_542.log &
python AGN_setup.py 543 #> AGN_logs/AGN_LX_table_543.log &
python AGN_setup.py 544 #> AGN_logs/AGN_LX_table_544.log &
python AGN_setup.py 545 #> AGN_logs/AGN_LX_table_545.log &
python AGN_setup.py 546 #> AGN_logs/AGN_LX_table_546.log &
python AGN_setup.py 547 #> AGN_logs/AGN_LX_table_547.log &
python AGN_setup.py 548 #> AGN_logs/AGN_LX_table_548.log &
python AGN_setup.py 549 #> AGN_logs/AGN_LX_table_549.log &
python AGN_setup.py 550 #> AGN_logs/AGN_LX_table_550.log &
python AGN_setup.py 551 #> AGN_logs/AGN_LX_table_551.log &
python AGN_setup.py 552 #> AGN_logs/AGN_LX_table_552.log &
python AGN_setup.py 553 #> AGN_logs/AGN_LX_table_553.log &
python AGN_setup.py 554 #> AGN_logs/AGN_LX_table_554.log &
python AGN_setup.py 555 #> AGN_logs/AGN_LX_table_555.log &
python AGN_setup.py 556 #> AGN_logs/AGN_LX_table_556.log &
python AGN_setup.py 557 #> AGN_logs/AGN_LX_table_557.log &
python AGN_setup.py 558 #> AGN_logs/AGN_LX_table_558.log &
python AGN_setup.py 559 #> AGN_logs/AGN_LX_table_559.log &
python AGN_setup.py 560 #> AGN_logs/AGN_LX_table_560.log &
python AGN_setup.py 561 #> AGN_logs/AGN_LX_table_561.log &
python AGN_setup.py 562 #> AGN_logs/AGN_LX_table_562.log &
python AGN_setup.py 563 #> AGN_logs/AGN_LX_table_563.log &
python AGN_setup.py 564 #> AGN_logs/AGN_LX_table_564.log &
python AGN_setup.py 565 #> AGN_logs/AGN_LX_table_565.log &
python AGN_setup.py 566 #> AGN_logs/AGN_LX_table_566.log &
python AGN_setup.py 567 #> AGN_logs/AGN_LX_table_567.log &
python AGN_setup.py 568 #> AGN_logs/AGN_LX_table_568.log &
python AGN_setup.py 569 #> AGN_logs/AGN_LX_table_569.log &
python AGN_setup.py 570 #> AGN_logs/AGN_LX_table_570.log &
python AGN_setup.py 571 #> AGN_logs/AGN_LX_table_571.log &
python AGN_setup.py 572 #> AGN_logs/AGN_LX_table_572.log &
python AGN_setup.py 573 #> AGN_logs/AGN_LX_table_573.log &
python AGN_setup.py 574 #> AGN_logs/AGN_LX_table_574.log &
python AGN_setup.py 575 #> AGN_logs/AGN_LX_table_575.log &
python AGN_setup.py 576 #> AGN_logs/AGN_LX_table_576.log &
python AGN_setup.py 577 #> AGN_logs/AGN_LX_table_577.log &
python AGN_setup.py 578 #> AGN_logs/AGN_LX_table_578.log &
python AGN_setup.py 579 #> AGN_logs/AGN_LX_table_579.log &
python AGN_setup.py 580 #> AGN_logs/AGN_LX_table_580.log &
python AGN_setup.py 581 #> AGN_logs/AGN_LX_table_581.log &
python AGN_setup.py 582 #> AGN_logs/AGN_LX_table_582.log &
python AGN_setup.py 583 #> AGN_logs/AGN_LX_table_583.log &
python AGN_setup.py 584 #> AGN_logs/AGN_LX_table_584.log &
python AGN_setup.py 585 #> AGN_logs/AGN_LX_table_585.log &
python AGN_setup.py 586 #> AGN_logs/AGN_LX_table_586.log &
python AGN_setup.py 587 #> AGN_logs/AGN_LX_table_587.log &
python AGN_setup.py 588 #> AGN_logs/AGN_LX_table_588.log &
python AGN_setup.py 589 #> AGN_logs/AGN_LX_table_589.log &
python AGN_setup.py 590 #> AGN_logs/AGN_LX_table_590.log &
python AGN_setup.py 591 #> AGN_logs/AGN_LX_table_591.log &
python AGN_setup.py 592 #> AGN_logs/AGN_LX_table_592.log &
python AGN_setup.py 593 #> AGN_logs/AGN_LX_table_593.log &
python AGN_setup.py 594 #> AGN_logs/AGN_LX_table_594.log &
python AGN_setup.py 595 #> AGN_logs/AGN_LX_table_595.log &
python AGN_setup.py 596 #> AGN_logs/AGN_LX_table_596.log &
python AGN_setup.py 597 #> AGN_logs/AGN_LX_table_597.log &
python AGN_setup.py 598 #> AGN_logs/AGN_LX_table_598.log &
python AGN_setup.py 599 #> AGN_logs/AGN_LX_table_599.log &


nohup python AGN_setup_XYZ.py 0   > AGN_logs/AGN_LX_table_0.log &
nohup python AGN_setup_XYZ.py 1   > AGN_logs/AGN_LX_table_1.log &
nohup python AGN_setup_XYZ.py 2   > AGN_logs/AGN_LX_table_2.log &
nohup python AGN_setup_XYZ.py 3   > AGN_logs/AGN_LX_table_3.log &
nohup python AGN_setup_XYZ.py 4   > AGN_logs/AGN_LX_table_4.log &
nohup python AGN_setup_XYZ.py 5   > AGN_logs/AGN_LX_table_5.log &
nohup python AGN_setup_XYZ.py 6   > AGN_logs/AGN_LX_table_6.log &
nohup python AGN_setup_XYZ.py 7   > AGN_logs/AGN_LX_table_7.log &
nohup python AGN_setup_XYZ.py 8   > AGN_logs/AGN_LX_table_8.log &
nohup python AGN_setup_XYZ.py 9   > AGN_logs/AGN_LX_table_9.log &
nohup python AGN_setup_XYZ.py 10  > AGN_logs/AGN_LX_table_10.log &
nohup python AGN_setup_XYZ.py 11  > AGN_logs/AGN_LX_table_11.log &
nohup python AGN_setup_XYZ.py 12  > AGN_logs/AGN_LX_table_12.log &
nohup python AGN_setup_XYZ.py 13  > AGN_logs/AGN_LX_table_13.log &
nohup python AGN_setup_XYZ.py 14  > AGN_logs/AGN_LX_table_14.log &
nohup python AGN_setup_XYZ.py 15  > AGN_logs/AGN_LX_table_15.log &
nohup python AGN_setup_XYZ.py 16  > AGN_logs/AGN_LX_table_16.log &
nohup python AGN_setup_XYZ.py 17  > AGN_logs/AGN_LX_table_17.log &
nohup python AGN_setup_XYZ.py 18  > AGN_logs/AGN_LX_table_18.log &
nohup python AGN_setup_XYZ.py 19  > AGN_logs/AGN_LX_table_19.log &
nohup python AGN_setup_XYZ.py 20  > AGN_logs/AGN_LX_table_20.log &
nohup python AGN_setup_XYZ.py 21  > AGN_logs/AGN_LX_table_21.log &
nohup python AGN_setup_XYZ.py 22  > AGN_logs/AGN_LX_table_22.log &
nohup python AGN_setup_XYZ.py 23  > AGN_logs/AGN_LX_table_23.log &
nohup python AGN_setup_XYZ.py 24  > AGN_logs/AGN_LX_table_24.log &
nohup python AGN_setup_XYZ.py 25  > AGN_logs/AGN_LX_table_25.log &
nohup python AGN_setup_XYZ.py 26  > AGN_logs/AGN_LX_table_26.log &
nohup python AGN_setup_XYZ.py 27  > AGN_logs/AGN_LX_table_27.log &
nohup python AGN_setup_XYZ.py 28  > AGN_logs/AGN_LX_table_28.log &
nohup python AGN_setup_XYZ.py 29  > AGN_logs/AGN_LX_table_29.log &
nohup python AGN_setup_XYZ.py 30  > AGN_logs/AGN_LX_table_30.log &
python AGN_setup_XYZ.py 31  #> AGN_logs/AGN_LX_table_31.log &
python AGN_setup_XYZ.py 32  #> AGN_logs/AGN_LX_table_32.log &
python AGN_setup_XYZ.py 33  #> AGN_logs/AGN_LX_table_33.log &
python AGN_setup_XYZ.py 34  #> AGN_logs/AGN_LX_table_34.log &
python AGN_setup_XYZ.py 35  #> AGN_logs/AGN_LX_table_35.log &
python AGN_setup_XYZ.py 36  #> AGN_logs/AGN_LX_table_36.log &
python AGN_setup_XYZ.py 37  #> AGN_logs/AGN_LX_table_37.log &
python AGN_setup_XYZ.py 38  #> AGN_logs/AGN_LX_table_38.log &
python AGN_setup_XYZ.py 39  #> AGN_logs/AGN_LX_table_39.log &
python AGN_setup_XYZ.py 40  #> AGN_logs/AGN_LX_table_40.log &
python AGN_setup_XYZ.py 41  #> AGN_logs/AGN_LX_table_41.log &
python AGN_setup_XYZ.py 42  #> AGN_logs/AGN_LX_table_42.log &
python AGN_setup_XYZ.py 43  #> AGN_logs/AGN_LX_table_43.log &
python AGN_setup_XYZ.py 44  #> AGN_logs/AGN_LX_table_44.log &
python AGN_setup_XYZ.py 45  #> AGN_logs/AGN_LX_table_45.log &
python AGN_setup_XYZ.py 46  #> AGN_logs/AGN_LX_table_46.log &
python AGN_setup_XYZ.py 47  #> AGN_logs/AGN_LX_table_47.log &
python AGN_setup_XYZ.py 48  #> AGN_logs/AGN_LX_table_48.log &
python AGN_setup_XYZ.py 49  #> AGN_logs/AGN_LX_table_49.log &
python AGN_setup_XYZ.py 50  #> AGN_logs/AGN_LX_table_50.log &
python AGN_setup_XYZ.py 51  #> AGN_logs/AGN_LX_table_51.log &
python AGN_setup_XYZ.py 52  #> AGN_logs/AGN_LX_table_52.log &
python AGN_setup_XYZ.py 53  #> AGN_logs/AGN_LX_table_53.log &
python AGN_setup_XYZ.py 54  #> AGN_logs/AGN_LX_table_54.log &
python AGN_setup_XYZ.py 55  #> AGN_logs/AGN_LX_table_55.log &
python AGN_setup_XYZ.py 56  #> AGN_logs/AGN_LX_table_56.log &
python AGN_setup_XYZ.py 57  #> AGN_logs/AGN_LX_table_57.log &
python AGN_setup_XYZ.py 58  #> AGN_logs/AGN_LX_table_58.log &
python AGN_setup_XYZ.py 59  #> AGN_logs/AGN_LX_table_59.log &
python AGN_setup_XYZ.py 60  #> AGN_logs/AGN_LX_table_60.log &
python AGN_setup_XYZ.py 61  #> AGN_logs/AGN_LX_table_61.log &
python AGN_setup_XYZ.py 62  #> AGN_logs/AGN_LX_table_62.log &
python AGN_setup_XYZ.py 63  #> AGN_logs/AGN_LX_table_63.log &
python AGN_setup_XYZ.py 64  #> AGN_logs/AGN_LX_table_64.log &
python AGN_setup_XYZ.py 65  #> AGN_logs/AGN_LX_table_65.log &
python AGN_setup_XYZ.py 66  #> AGN_logs/AGN_LX_table_66.log &
python AGN_setup_XYZ.py 67  #> AGN_logs/AGN_LX_table_67.log &
python AGN_setup_XYZ.py 68  #> AGN_logs/AGN_LX_table_68.log &
python AGN_setup_XYZ.py 69  #> AGN_logs/AGN_LX_table_69.log &
python AGN_setup_XYZ.py 70  #> AGN_logs/AGN_LX_table_70.log &
python AGN_setup_XYZ.py 71  #> AGN_logs/AGN_LX_table_71.log &
python AGN_setup_XYZ.py 72  #> AGN_logs/AGN_LX_table_72.log &
python AGN_setup_XYZ.py 73  #> AGN_logs/AGN_LX_table_73.log &
python AGN_setup_XYZ.py 74  #> AGN_logs/AGN_LX_table_74.log &
python AGN_setup_XYZ.py 75  #> AGN_logs/AGN_LX_table_75.log &
python AGN_setup_XYZ.py 76  #> AGN_logs/AGN_LX_table_76.log &
python AGN_setup_XYZ.py 77  #> AGN_logs/AGN_LX_table_77.log &
python AGN_setup_XYZ.py 78  #> AGN_logs/AGN_LX_table_78.log &
python AGN_setup_XYZ.py 79  #> AGN_logs/AGN_LX_table_79.log &
python AGN_setup_XYZ.py 80  #> AGN_logs/AGN_LX_table_80.log &
python AGN_setup_XYZ.py 81  #> AGN_logs/AGN_LX_table_81.log &
python AGN_setup_XYZ.py 82  #> AGN_logs/AGN_LX_table_82.log &
python AGN_setup_XYZ.py 83  #> AGN_logs/AGN_LX_table_83.log &
python AGN_setup_XYZ.py 84  #> AGN_logs/AGN_LX_table_84.log &
python AGN_setup_XYZ.py 85  #> AGN_logs/AGN_LX_table_85.log &
python AGN_setup_XYZ.py 86  #> AGN_logs/AGN_LX_table_86.log &
python AGN_setup_XYZ.py 87  #> AGN_logs/AGN_LX_table_87.log &
python AGN_setup_XYZ.py 88  #> AGN_logs/AGN_LX_table_88.log &
python AGN_setup_XYZ.py 89  #> AGN_logs/AGN_LX_table_89.log &
python AGN_setup_XYZ.py 90  #> AGN_logs/AGN_LX_table_90.log &
python AGN_setup_XYZ.py 91  #> AGN_logs/AGN_LX_table_91.log &
python AGN_setup_XYZ.py 92  #> AGN_logs/AGN_LX_table_92.log &
python AGN_setup_XYZ.py 93  #> AGN_logs/AGN_LX_table_93.log &
python AGN_setup_XYZ.py 94  #> AGN_logs/AGN_LX_table_94.log &
python AGN_setup_XYZ.py 95  #> AGN_logs/AGN_LX_table_95.log &
python AGN_setup_XYZ.py 96  #> AGN_logs/AGN_LX_table_96.log &
python AGN_setup_XYZ.py 97  #> AGN_logs/AGN_LX_table_97.log &
python AGN_setup_XYZ.py 98  #> AGN_logs/AGN_LX_table_98.log &
python AGN_setup_XYZ.py 99  #> AGN_logs/AGN_LX_table_99.log &
python AGN_setup_XYZ.py 100 #> AGN_logs/AGN_LX_table_100.log &
python AGN_setup_XYZ.py 101 #> AGN_logs/AGN_LX_table_101.log &
python AGN_setup_XYZ.py 102 #> AGN_logs/AGN_LX_table_102.log &
python AGN_setup_XYZ.py 103 #> AGN_logs/AGN_LX_table_103.log &
python AGN_setup_XYZ.py 104 #> AGN_logs/AGN_LX_table_104.log &
python AGN_setup_XYZ.py 105 #> AGN_logs/AGN_LX_table_105.log &
python AGN_setup_XYZ.py 106 #> AGN_logs/AGN_LX_table_106.log &
python AGN_setup_XYZ.py 107 #> AGN_logs/AGN_LX_table_107.log &
python AGN_setup_XYZ.py 108 #> AGN_logs/AGN_LX_table_108.log &
python AGN_setup_XYZ.py 109 #> AGN_logs/AGN_LX_table_109.log &
python AGN_setup_XYZ.py 110 #> AGN_logs/AGN_LX_table_110.log &
python AGN_setup_XYZ.py 111 #> AGN_logs/AGN_LX_table_111.log &
python AGN_setup_XYZ.py 112 #> AGN_logs/AGN_LX_table_112.log &
python AGN_setup_XYZ.py 113 #> AGN_logs/AGN_LX_table_113.log &
python AGN_setup_XYZ.py 114 #> AGN_logs/AGN_LX_table_114.log &
python AGN_setup_XYZ.py 115 #> AGN_logs/AGN_LX_table_115.log &
python AGN_setup_XYZ.py 116 #> AGN_logs/AGN_LX_table_116.log &
python AGN_setup_XYZ.py 117 #> AGN_logs/AGN_LX_table_117.log &
python AGN_setup_XYZ.py 118 #> AGN_logs/AGN_LX_table_118.log &
python AGN_setup_XYZ.py 119 #> AGN_logs/AGN_LX_table_119.log &
python AGN_setup_XYZ.py 120 #> AGN_logs/AGN_LX_table_120.log &
python AGN_setup_XYZ.py 121 #> AGN_logs/AGN_LX_table_121.log &
python AGN_setup_XYZ.py 122 #> AGN_logs/AGN_LX_table_122.log &
python AGN_setup_XYZ.py 123 #> AGN_logs/AGN_LX_table_123.log &
python AGN_setup_XYZ.py 124 #> AGN_logs/AGN_LX_table_124.log &
python AGN_setup_XYZ.py 125 #> AGN_logs/AGN_LX_table_125.log &
python AGN_setup_XYZ.py 126 #> AGN_logs/AGN_LX_table_126.log &
python AGN_setup_XYZ.py 127 #> AGN_logs/AGN_LX_table_127.log &
python AGN_setup_XYZ.py 128 #> AGN_logs/AGN_LX_table_128.log &
python AGN_setup_XYZ.py 129 #> AGN_logs/AGN_LX_table_129.log &
python AGN_setup_XYZ.py 130 #> AGN_logs/AGN_LX_table_130.log &
python AGN_setup_XYZ.py 131 #> AGN_logs/AGN_LX_table_131.log &
python AGN_setup_XYZ.py 132 #> AGN_logs/AGN_LX_table_132.log &
python AGN_setup_XYZ.py 133 #> AGN_logs/AGN_LX_table_133.log &
python AGN_setup_XYZ.py 134 #> AGN_logs/AGN_LX_table_134.log &
python AGN_setup_XYZ.py 135 #> AGN_logs/AGN_LX_table_135.log &
python AGN_setup_XYZ.py 136 #> AGN_logs/AGN_LX_table_136.log &
python AGN_setup_XYZ.py 137 #> AGN_logs/AGN_LX_table_137.log &
python AGN_setup_XYZ.py 138 #> AGN_logs/AGN_LX_table_138.log &
python AGN_setup_XYZ.py 139 #> AGN_logs/AGN_LX_table_139.log &
python AGN_setup_XYZ.py 140 #> AGN_logs/AGN_LX_table_140.log &
python AGN_setup_XYZ.py 141 #> AGN_logs/AGN_LX_table_141.log &
python AGN_setup_XYZ.py 142 #> AGN_logs/AGN_LX_table_142.log &
python AGN_setup_XYZ.py 143 #> AGN_logs/AGN_LX_table_143.log &
python AGN_setup_XYZ.py 144 #> AGN_logs/AGN_LX_table_144.log &
python AGN_setup_XYZ.py 145 #> AGN_logs/AGN_LX_table_145.log &
python AGN_setup_XYZ.py 146 #> AGN_logs/AGN_LX_table_146.log &
python AGN_setup_XYZ.py 147 #> AGN_logs/AGN_LX_table_147.log &
python AGN_setup_XYZ.py 148 #> AGN_logs/AGN_LX_table_148.log &
python AGN_setup_XYZ.py 149 #> AGN_logs/AGN_LX_table_149.log &
python AGN_setup_XYZ.py 150 #> AGN_logs/AGN_LX_table_150.log &
python AGN_setup_XYZ.py 151 #> AGN_logs/AGN_LX_table_151.log &
python AGN_setup_XYZ.py 152 #> AGN_logs/AGN_LX_table_152.log &
python AGN_setup_XYZ.py 153 #> AGN_logs/AGN_LX_table_153.log &
python AGN_setup_XYZ.py 154 #> AGN_logs/AGN_LX_table_154.log &
python AGN_setup_XYZ.py 155 #> AGN_logs/AGN_LX_table_155.log &
python AGN_setup_XYZ.py 156 #> AGN_logs/AGN_LX_table_156.log &
python AGN_setup_XYZ.py 157 #> AGN_logs/AGN_LX_table_157.log &
python AGN_setup_XYZ.py 158 #> AGN_logs/AGN_LX_table_158.log &
python AGN_setup_XYZ.py 159 #> AGN_logs/AGN_LX_table_159.log &
python AGN_setup_XYZ.py 160 #> AGN_logs/AGN_LX_table_160.log &
python AGN_setup_XYZ.py 161 #> AGN_logs/AGN_LX_table_161.log &
python AGN_setup_XYZ.py 162 #> AGN_logs/AGN_LX_table_162.log &
python AGN_setup_XYZ.py 163 #> AGN_logs/AGN_LX_table_163.log &
python AGN_setup_XYZ.py 164 #> AGN_logs/AGN_LX_table_164.log &
python AGN_setup_XYZ.py 165 #> AGN_logs/AGN_LX_table_165.log &
python AGN_setup_XYZ.py 166 #> AGN_logs/AGN_LX_table_166.log &
python AGN_setup_XYZ.py 167 #> AGN_logs/AGN_LX_table_167.log &
python AGN_setup_XYZ.py 168 #> AGN_logs/AGN_LX_table_168.log &
python AGN_setup_XYZ.py 169 #> AGN_logs/AGN_LX_table_169.log &
python AGN_setup_XYZ.py 170 #> AGN_logs/AGN_LX_table_170.log &
python AGN_setup_XYZ.py 171 #> AGN_logs/AGN_LX_table_171.log &
python AGN_setup_XYZ.py 172 #> AGN_logs/AGN_LX_table_172.log &
python AGN_setup_XYZ.py 173 #> AGN_logs/AGN_LX_table_173.log &
python AGN_setup_XYZ.py 174 #> AGN_logs/AGN_LX_table_174.log &
python AGN_setup_XYZ.py 175 #> AGN_logs/AGN_LX_table_175.log &
python AGN_setup_XYZ.py 176 #> AGN_logs/AGN_LX_table_176.log &
python AGN_setup_XYZ.py 177 #> AGN_logs/AGN_LX_table_177.log &
python AGN_setup_XYZ.py 178 #> AGN_logs/AGN_LX_table_178.log &
python AGN_setup_XYZ.py 179 #> AGN_logs/AGN_LX_table_179.log &
python AGN_setup_XYZ.py 180 #> AGN_logs/AGN_LX_table_180.log &
python AGN_setup_XYZ.py 181 #> AGN_logs/AGN_LX_table_181.log &
python AGN_setup_XYZ.py 182 #> AGN_logs/AGN_LX_table_182.log &
python AGN_setup_XYZ.py 183 #> AGN_logs/AGN_LX_table_183.log &
python AGN_setup_XYZ.py 184 #> AGN_logs/AGN_LX_table_184.log &
python AGN_setup_XYZ.py 185 #> AGN_logs/AGN_LX_table_185.log &
python AGN_setup_XYZ.py 186 #> AGN_logs/AGN_LX_table_186.log &
python AGN_setup_XYZ.py 187 #> AGN_logs/AGN_LX_table_187.log &
python AGN_setup_XYZ.py 188 #> AGN_logs/AGN_LX_table_188.log &
python AGN_setup_XYZ.py 189 #> AGN_logs/AGN_LX_table_189.log &
python AGN_setup_XYZ.py 190 #> AGN_logs/AGN_LX_table_190.log &
python AGN_setup_XYZ.py 191 #> AGN_logs/AGN_LX_table_191.log &
python AGN_setup_XYZ.py 192 #> AGN_logs/AGN_LX_table_192.log &
python AGN_setup_XYZ.py 193 #> AGN_logs/AGN_LX_table_193.log &
python AGN_setup_XYZ.py 194 #> AGN_logs/AGN_LX_table_194.log &
python AGN_setup_XYZ.py 195 #> AGN_logs/AGN_LX_table_195.log &
python AGN_setup_XYZ.py 196 #> AGN_logs/AGN_LX_table_196.log &
python AGN_setup_XYZ.py 197 #> AGN_logs/AGN_LX_table_197.log &
python AGN_setup_XYZ.py 198 #> AGN_logs/AGN_LX_table_198.log &
python AGN_setup_XYZ.py 199 #> AGN_logs/AGN_LX_table_199.log &
python AGN_setup_XYZ.py 200 #> AGN_logs/AGN_LX_table_200.log &
python AGN_setup_XYZ.py 201 #> AGN_logs/AGN_LX_table_201.log &
python AGN_setup_XYZ.py 202 #> AGN_logs/AGN_LX_table_202.log &
python AGN_setup_XYZ.py 203 #> AGN_logs/AGN_LX_table_203.log &
python AGN_setup_XYZ.py 204 #> AGN_logs/AGN_LX_table_204.log &
python AGN_setup_XYZ.py 205 #> AGN_logs/AGN_LX_table_205.log &
python AGN_setup_XYZ.py 206 #> AGN_logs/AGN_LX_table_206.log &
python AGN_setup_XYZ.py 207 #> AGN_logs/AGN_LX_table_207.log &
python AGN_setup_XYZ.py 208 #> AGN_logs/AGN_LX_table_208.log &
python AGN_setup_XYZ.py 209 #> AGN_logs/AGN_LX_table_209.log &
python AGN_setup_XYZ.py 210 #> AGN_logs/AGN_LX_table_210.log &
python AGN_setup_XYZ.py 211 #> AGN_logs/AGN_LX_table_211.log &
python AGN_setup_XYZ.py 212 #> AGN_logs/AGN_LX_table_212.log &
python AGN_setup_XYZ.py 213 #> AGN_logs/AGN_LX_table_213.log &

python AGN_setup_XYZ.py 214 #> AGN_logs/AGN_LX_table_214.log &
python AGN_setup_XYZ.py 215 #> AGN_logs/AGN_LX_table_215.log &
python AGN_setup_XYZ.py 216 #> AGN_logs/AGN_LX_table_216.log &
python AGN_setup_XYZ.py 217 #> AGN_logs/AGN_LX_table_217.log &
python AGN_setup_XYZ.py 218 #> AGN_logs/AGN_LX_table_218.log &
python AGN_setup_XYZ.py 219 #> AGN_logs/AGN_LX_table_219.log &
python AGN_setup_XYZ.py 220 #> AGN_logs/AGN_LX_table_220.log &
python AGN_setup_XYZ.py 221 #> AGN_logs/AGN_LX_table_221.log &
python AGN_setup_XYZ.py 222 #> AGN_logs/AGN_LX_table_222.log &
python AGN_setup_XYZ.py 223 #> AGN_logs/AGN_LX_table_223.log &
python AGN_setup_XYZ.py 224 #> AGN_logs/AGN_LX_table_224.log &
python AGN_setup_XYZ.py 225 #> AGN_logs/AGN_LX_table_225.log &
python AGN_setup_XYZ.py 226 #> AGN_logs/AGN_LX_table_226.log &
python AGN_setup_XYZ.py 227 #> AGN_logs/AGN_LX_table_227.log &
python AGN_setup_XYZ.py 228 #> AGN_logs/AGN_LX_table_228.log &
python AGN_setup_XYZ.py 229 #> AGN_logs/AGN_LX_table_229.log &
python AGN_setup_XYZ.py 230 #> AGN_logs/AGN_LX_table_230.log &
python AGN_setup_XYZ.py 231 #> AGN_logs/AGN_LX_table_231.log &
python AGN_setup_XYZ.py 232 #> AGN_logs/AGN_LX_table_232.log &
python AGN_setup_XYZ.py 233 #> AGN_logs/AGN_LX_table_233.log &
python AGN_setup_XYZ.py 234 #> AGN_logs/AGN_LX_table_234.log &
python AGN_setup_XYZ.py 235 #> AGN_logs/AGN_LX_table_235.log &
python AGN_setup_XYZ.py 236 #> AGN_logs/AGN_LX_table_236.log &
python AGN_setup_XYZ.py 237 #> AGN_logs/AGN_LX_table_237.log &
python AGN_setup_XYZ.py 238 #> AGN_logs/AGN_LX_table_238.log &
python AGN_setup_XYZ.py 239 #> AGN_logs/AGN_LX_table_239.log &
python AGN_setup_XYZ.py 240 #> AGN_logs/AGN_LX_table_240.log &
python AGN_setup_XYZ.py 241 #> AGN_logs/AGN_LX_table_241.log &
python AGN_setup_XYZ.py 242 #> AGN_logs/AGN_LX_table_242.log &
python AGN_setup_XYZ.py 243 #> AGN_logs/AGN_LX_table_243.log &
python AGN_setup_XYZ.py 244 #> AGN_logs/AGN_LX_table_244.log &
python AGN_setup_XYZ.py 245 #> AGN_logs/AGN_LX_table_245.log &
python AGN_setup_XYZ.py 246 #> AGN_logs/AGN_LX_table_246.log &
python AGN_setup_XYZ.py 247 #> AGN_logs/AGN_LX_table_247.log &
python AGN_setup_XYZ.py 248 #> AGN_logs/AGN_LX_table_248.log &
python AGN_setup_XYZ.py 249 #> AGN_logs/AGN_LX_table_249.log &
python AGN_setup_XYZ.py 250 #> AGN_logs/AGN_LX_table_250.log &
python AGN_setup_XYZ.py 251 #> AGN_logs/AGN_LX_table_251.log &
python AGN_setup_XYZ.py 252 #> AGN_logs/AGN_LX_table_252.log &
python AGN_setup_XYZ.py 253 #> AGN_logs/AGN_LX_table_253.log &
python AGN_setup_XYZ.py 254 #> AGN_logs/AGN_LX_table_254.log &
python AGN_setup_XYZ.py 255 #> AGN_logs/AGN_LX_table_255.log &
python AGN_setup_XYZ.py 256 #> AGN_logs/AGN_LX_table_256.log &
python AGN_setup_XYZ.py 257 #> AGN_logs/AGN_LX_table_257.log &
python AGN_setup_XYZ.py 258 #> AGN_logs/AGN_LX_table_258.log &
python AGN_setup_XYZ.py 259 #> AGN_logs/AGN_LX_table_259.log &
python AGN_setup_XYZ.py 260 #> AGN_logs/AGN_LX_table_260.log &
python AGN_setup_XYZ.py 261 #> AGN_logs/AGN_LX_table_261.log &
python AGN_setup_XYZ.py 262 #> AGN_logs/AGN_LX_table_262.log &
python AGN_setup_XYZ.py 263 #> AGN_logs/AGN_LX_table_263.log &
python AGN_setup_XYZ.py 264 #> AGN_logs/AGN_LX_table_264.log &
python AGN_setup_XYZ.py 265 #> AGN_logs/AGN_LX_table_265.log &
python AGN_setup_XYZ.py 266 #> AGN_logs/AGN_LX_table_266.log &
python AGN_setup_XYZ.py 267 #> AGN_logs/AGN_LX_table_267.log &
python AGN_setup_XYZ.py 268 #> AGN_logs/AGN_LX_table_268.log &
python AGN_setup_XYZ.py 269 #> AGN_logs/AGN_LX_table_269.log &
python AGN_setup_XYZ.py 270 #> AGN_logs/AGN_LX_table_270.log &
python AGN_setup_XYZ.py 271 #> AGN_logs/AGN_LX_table_271.log &
python AGN_setup_XYZ.py 272 #> AGN_logs/AGN_LX_table_272.log &
python AGN_setup_XYZ.py 273 #> AGN_logs/AGN_LX_table_273.log &
python AGN_setup_XYZ.py 274 #> AGN_logs/AGN_LX_table_274.log &
python AGN_setup_XYZ.py 275 #> AGN_logs/AGN_LX_table_275.log &
python AGN_setup_XYZ.py 276 #> AGN_logs/AGN_LX_table_276.log &
python AGN_setup_XYZ.py 277 #> AGN_logs/AGN_LX_table_277.log &
python AGN_setup_XYZ.py 278 #> AGN_logs/AGN_LX_table_278.log &
python AGN_setup_XYZ.py 279 #> AGN_logs/AGN_LX_table_279.log &
python AGN_setup_XYZ.py 280 #> AGN_logs/AGN_LX_table_280.log &
python AGN_setup_XYZ.py 281 #> AGN_logs/AGN_LX_table_281.log &
python AGN_setup_XYZ.py 282 #> AGN_logs/AGN_LX_table_282.log &
python AGN_setup_XYZ.py 283 #> AGN_logs/AGN_LX_table_283.log &
python AGN_setup_XYZ.py 284 #> AGN_logs/AGN_LX_table_284.log &
python AGN_setup_XYZ.py 285 #> AGN_logs/AGN_LX_table_285.log &
python AGN_setup_XYZ.py 286 #> AGN_logs/AGN_LX_table_286.log &
python AGN_setup_XYZ.py 287 #> AGN_logs/AGN_LX_table_287.log &
python AGN_setup_XYZ.py 288 #> AGN_logs/AGN_LX_table_288.log &
python AGN_setup_XYZ.py 289 #> AGN_logs/AGN_LX_table_289.log &
python AGN_setup_XYZ.py 290 #> AGN_logs/AGN_LX_table_290.log &
python AGN_setup_XYZ.py 291 #> AGN_logs/AGN_LX_table_291.log &
python AGN_setup_XYZ.py 292 #> AGN_logs/AGN_LX_table_292.log &
python AGN_setup_XYZ.py 293 #> AGN_logs/AGN_LX_table_293.log &
python AGN_setup_XYZ.py 294 #> AGN_logs/AGN_LX_table_294.log &
python AGN_setup_XYZ.py 295 #> AGN_logs/AGN_LX_table_295.log &
python AGN_setup_XYZ.py 296 #> AGN_logs/AGN_LX_table_296.log &
python AGN_setup_XYZ.py 297 #> AGN_logs/AGN_LX_table_297.log &
python AGN_setup_XYZ.py 298 #> AGN_logs/AGN_LX_table_298.log &
python AGN_setup_XYZ.py 299 #> AGN_logs/AGN_LX_table_299.log &
python AGN_setup_XYZ.py 300 #> AGN_logs/AGN_LX_table_300.log &
python AGN_setup_XYZ.py 301 #> AGN_logs/AGN_LX_table_301.log &
python AGN_setup_XYZ.py 302 #> AGN_logs/AGN_LX_table_302.log &
python AGN_setup_XYZ.py 303 #> AGN_logs/AGN_LX_table_303.log &
python AGN_setup_XYZ.py 304 #> AGN_logs/AGN_LX_table_304.log &
python AGN_setup_XYZ.py 305 #> AGN_logs/AGN_LX_table_305.log &
python AGN_setup_XYZ.py 306 #> AGN_logs/AGN_LX_table_306.log &
python AGN_setup_XYZ.py 307 #> AGN_logs/AGN_LX_table_307.log &
python AGN_setup_XYZ.py 308 #> AGN_logs/AGN_LX_table_308.log &
python AGN_setup_XYZ.py 309 #> AGN_logs/AGN_LX_table_309.log &
python AGN_setup_XYZ.py 310 #> AGN_logs/AGN_LX_table_310.log &
python AGN_setup_XYZ.py 311 #> AGN_logs/AGN_LX_table_311.log &
python AGN_setup_XYZ.py 312 #> AGN_logs/AGN_LX_table_312.log &
python AGN_setup_XYZ.py 313 #> AGN_logs/AGN_LX_table_313.log &
python AGN_setup_XYZ.py 314 #> AGN_logs/AGN_LX_table_314.log &
python AGN_setup_XYZ.py 315 #> AGN_logs/AGN_LX_table_315.log &
python AGN_setup_XYZ.py 316 #> AGN_logs/AGN_LX_table_316.log &
python AGN_setup_XYZ.py 317 #> AGN_logs/AGN_LX_table_317.log &
python AGN_setup_XYZ.py 318 #> AGN_logs/AGN_LX_table_318.log &
python AGN_setup_XYZ.py 319 #> AGN_logs/AGN_LX_table_319.log &
python AGN_setup_XYZ.py 320 #> AGN_logs/AGN_LX_table_320.log &
python AGN_setup_XYZ.py 321 #> AGN_logs/AGN_LX_table_321.log &
python AGN_setup_XYZ.py 322 #> AGN_logs/AGN_LX_table_322.log &
python AGN_setup_XYZ.py 323 #> AGN_logs/AGN_LX_table_323.log &
python AGN_setup_XYZ.py 324 #> AGN_logs/AGN_LX_table_324.log &
python AGN_setup_XYZ.py 325 #> AGN_logs/AGN_LX_table_325.log &
python AGN_setup_XYZ.py 326 #> AGN_logs/AGN_LX_table_326.log &
python AGN_setup_XYZ.py 327 #> AGN_logs/AGN_LX_table_327.log &
python AGN_setup_XYZ.py 328 #> AGN_logs/AGN_LX_table_328.log &
python AGN_setup_XYZ.py 329 #> AGN_logs/AGN_LX_table_329.log &
python AGN_setup_XYZ.py 330 #> AGN_logs/AGN_LX_table_330.log &
python AGN_setup_XYZ.py 331 #> AGN_logs/AGN_LX_table_331.log &
python AGN_setup_XYZ.py 332 #> AGN_logs/AGN_LX_table_332.log &
python AGN_setup_XYZ.py 333 #> AGN_logs/AGN_LX_table_333.log &
python AGN_setup_XYZ.py 334 #> AGN_logs/AGN_LX_table_334.log &
python AGN_setup_XYZ.py 335 #> AGN_logs/AGN_LX_table_335.log &
python AGN_setup_XYZ.py 336 #> AGN_logs/AGN_LX_table_336.log &
python AGN_setup_XYZ.py 337 #> AGN_logs/AGN_LX_table_337.log &
python AGN_setup_XYZ.py 338 #> AGN_logs/AGN_LX_table_338.log &
python AGN_setup_XYZ.py 339 #> AGN_logs/AGN_LX_table_339.log &
python AGN_setup_XYZ.py 340 #> AGN_logs/AGN_LX_table_340.log &
python AGN_setup_XYZ.py 341 #> AGN_logs/AGN_LX_table_341.log &
python AGN_setup_XYZ.py 342 #> AGN_logs/AGN_LX_table_342.log &
python AGN_setup_XYZ.py 343 #> AGN_logs/AGN_LX_table_343.log &
python AGN_setup_XYZ.py 344 #> AGN_logs/AGN_LX_table_344.log &
python AGN_setup_XYZ.py 345 #> AGN_logs/AGN_LX_table_345.log &
python AGN_setup_XYZ.py 346 #> AGN_logs/AGN_LX_table_346.log &
python AGN_setup_XYZ.py 347 #> AGN_logs/AGN_LX_table_347.log &
python AGN_setup_XYZ.py 348 #> AGN_logs/AGN_LX_table_348.log &
python AGN_setup_XYZ.py 349 #> AGN_logs/AGN_LX_table_349.log &
python AGN_setup_XYZ.py 350 #> AGN_logs/AGN_LX_table_350.log &
python AGN_setup_XYZ.py 351 #> AGN_logs/AGN_LX_table_351.log &
python AGN_setup_XYZ.py 352 #> AGN_logs/AGN_LX_table_352.log &
python AGN_setup_XYZ.py 353 #> AGN_logs/AGN_LX_table_353.log &
python AGN_setup_XYZ.py 354 #> AGN_logs/AGN_LX_table_354.log &
python AGN_setup_XYZ.py 355 #> AGN_logs/AGN_LX_table_355.log &
python AGN_setup_XYZ.py 356 #> AGN_logs/AGN_LX_table_356.log &
python AGN_setup_XYZ.py 357 #> AGN_logs/AGN_LX_table_357.log &
python AGN_setup_XYZ.py 358 #> AGN_logs/AGN_LX_table_358.log &
python AGN_setup_XYZ.py 359 #> AGN_logs/AGN_LX_table_359.log &
python AGN_setup_XYZ.py 360 #> AGN_logs/AGN_LX_table_360.log &
python AGN_setup_XYZ.py 361 #> AGN_logs/AGN_LX_table_361.log &
python AGN_setup_XYZ.py 362 #> AGN_logs/AGN_LX_table_362.log &
python AGN_setup_XYZ.py 363 #> AGN_logs/AGN_LX_table_363.log &
python AGN_setup_XYZ.py 364 #> AGN_logs/AGN_LX_table_364.log &
python AGN_setup_XYZ.py 365 #> AGN_logs/AGN_LX_table_365.log &
python AGN_setup_XYZ.py 366 #> AGN_logs/AGN_LX_table_366.log &
python AGN_setup_XYZ.py 367 #> AGN_logs/AGN_LX_table_367.log &
python AGN_setup_XYZ.py 368 #> AGN_logs/AGN_LX_table_368.log &
python AGN_setup_XYZ.py 369 #> AGN_logs/AGN_LX_table_369.log &
python AGN_setup_XYZ.py 370 #> AGN_logs/AGN_LX_table_370.log &
python AGN_setup_XYZ.py 371 #> AGN_logs/AGN_LX_table_371.log &
python AGN_setup_XYZ.py 372 #> AGN_logs/AGN_LX_table_372.log &
python AGN_setup_XYZ.py 373 #> AGN_logs/AGN_LX_table_373.log &
python AGN_setup_XYZ.py 374 #> AGN_logs/AGN_LX_table_374.log &
python AGN_setup_XYZ.py 375 #> AGN_logs/AGN_LX_table_375.log &
python AGN_setup_XYZ.py 376 #> AGN_logs/AGN_LX_table_376.log &
python AGN_setup_XYZ.py 377 #> AGN_logs/AGN_LX_table_377.log &
python AGN_setup_XYZ.py 378 #> AGN_logs/AGN_LX_table_378.log &
python AGN_setup_XYZ.py 379 #> AGN_logs/AGN_LX_table_379.log &
python AGN_setup_XYZ.py 380 #> AGN_logs/AGN_LX_table_380.log &
python AGN_setup_XYZ.py 381 #> AGN_logs/AGN_LX_table_381.log &
python AGN_setup_XYZ.py 382 #> AGN_logs/AGN_LX_table_382.log &
python AGN_setup_XYZ.py 383 #> AGN_logs/AGN_LX_table_383.log &
python AGN_setup_XYZ.py 384 #> AGN_logs/AGN_LX_table_384.log &
python AGN_setup_XYZ.py 385 #> AGN_logs/AGN_LX_table_385.log &
python AGN_setup_XYZ.py 386 #> AGN_logs/AGN_LX_table_386.log &
python AGN_setup_XYZ.py 387 #> AGN_logs/AGN_LX_table_387.log &
python AGN_setup_XYZ.py 388 #> AGN_logs/AGN_LX_table_388.log &
python AGN_setup_XYZ.py 389 #> AGN_logs/AGN_LX_table_389.log &
python AGN_setup_XYZ.py 390 #> AGN_logs/AGN_LX_table_390.log &
python AGN_setup_XYZ.py 391 #> AGN_logs/AGN_LX_table_391.log &
python AGN_setup_XYZ.py 392 #> AGN_logs/AGN_LX_table_392.log &
python AGN_setup_XYZ.py 393 #> AGN_logs/AGN_LX_table_393.log &
python AGN_setup_XYZ.py 394 #> AGN_logs/AGN_LX_table_394.log &
python AGN_setup_XYZ.py 395 #> AGN_logs/AGN_LX_table_395.log &
python AGN_setup_XYZ.py 396 #> AGN_logs/AGN_LX_table_396.log &
python AGN_setup_XYZ.py 397 #> AGN_logs/AGN_LX_table_397.log &
python AGN_setup_XYZ.py 398 #> AGN_logs/AGN_LX_table_398.log &
python AGN_setup_XYZ.py 399 #> AGN_logs/AGN_LX_table_399.log &
python AGN_setup_XYZ.py 400 #> AGN_logs/AGN_LX_table_400.log &
python AGN_setup_XYZ.py 401 #> AGN_logs/AGN_LX_table_401.log &
python AGN_setup_XYZ.py 402 #> AGN_logs/AGN_LX_table_402.log &
python AGN_setup_XYZ.py 403 #> AGN_logs/AGN_LX_table_403.log &
python AGN_setup_XYZ.py 404 #> AGN_logs/AGN_LX_table_404.log &
python AGN_setup_XYZ.py 405 #> AGN_logs/AGN_LX_table_405.log &
python AGN_setup_XYZ.py 406 #> AGN_logs/AGN_LX_table_406.log &
python AGN_setup_XYZ.py 407 #> AGN_logs/AGN_LX_table_407.log &
python AGN_setup_XYZ.py 408 #> AGN_logs/AGN_LX_table_408.log &
python AGN_setup_XYZ.py 409 #> AGN_logs/AGN_LX_table_409.log &
python AGN_setup_XYZ.py 410 #> AGN_logs/AGN_LX_table_410.log &
python AGN_setup_XYZ.py 411 #> AGN_logs/AGN_LX_table_411.log &
python AGN_setup_XYZ.py 412 #> AGN_logs/AGN_LX_table_412.log &
python AGN_setup_XYZ.py 413 #> AGN_logs/AGN_LX_table_413.log &
python AGN_setup_XYZ.py 414 #> AGN_logs/AGN_LX_table_414.log &
python AGN_setup_XYZ.py 415 #> AGN_logs/AGN_LX_table_415.log &
python AGN_setup_XYZ.py 416 #> AGN_logs/AGN_LX_table_416.log &

python AGN_setup_XYZ.py 417 #> AGN_logs/AGN_LX_table_417.log &
python AGN_setup_XYZ.py 418 #> AGN_logs/AGN_LX_table_418.log &
python AGN_setup_XYZ.py 419 #> AGN_logs/AGN_LX_table_419.log &
python AGN_setup_XYZ.py 420 #> AGN_logs/AGN_LX_table_420.log &
python AGN_setup_XYZ.py 421 #> AGN_logs/AGN_LX_table_421.log &
python AGN_setup_XYZ.py 422 #> AGN_logs/AGN_LX_table_422.log &
python AGN_setup_XYZ.py 423 #> AGN_logs/AGN_LX_table_423.log &
python AGN_setup_XYZ.py 424 #> AGN_logs/AGN_LX_table_424.log &
python AGN_setup_XYZ.py 425 #> AGN_logs/AGN_LX_table_425.log &
python AGN_setup_XYZ.py 426 #> AGN_logs/AGN_LX_table_426.log &
python AGN_setup_XYZ.py 427 #> AGN_logs/AGN_LX_table_427.log &
python AGN_setup_XYZ.py 428 #> AGN_logs/AGN_LX_table_428.log &
python AGN_setup_XYZ.py 429 #> AGN_logs/AGN_LX_table_429.log &
python AGN_setup_XYZ.py 430 #> AGN_logs/AGN_LX_table_430.log &
python AGN_setup_XYZ.py 431 #> AGN_logs/AGN_LX_table_431.log &
python AGN_setup_XYZ.py 432 #> AGN_logs/AGN_LX_table_432.log &
python AGN_setup_XYZ.py 433 #> AGN_logs/AGN_LX_table_433.log &
python AGN_setup_XYZ.py 434 #> AGN_logs/AGN_LX_table_434.log &
python AGN_setup_XYZ.py 435 #> AGN_logs/AGN_LX_table_435.log &
python AGN_setup_XYZ.py 436 #> AGN_logs/AGN_LX_table_436.log &
python AGN_setup_XYZ.py 437 #> AGN_logs/AGN_LX_table_437.log &
python AGN_setup_XYZ.py 438 #> AGN_logs/AGN_LX_table_438.log &
python AGN_setup_XYZ.py 439 #> AGN_logs/AGN_LX_table_439.log &
python AGN_setup_XYZ.py 440 #> AGN_logs/AGN_LX_table_440.log &
python AGN_setup_XYZ.py 441 #> AGN_logs/AGN_LX_table_441.log &
python AGN_setup_XYZ.py 442 #> AGN_logs/AGN_LX_table_442.log &
python AGN_setup_XYZ.py 443 #> AGN_logs/AGN_LX_table_443.log &
python AGN_setup_XYZ.py 444 #> AGN_logs/AGN_LX_table_444.log &
python AGN_setup_XYZ.py 445 #> AGN_logs/AGN_LX_table_445.log &
python AGN_setup_XYZ.py 446 #> AGN_logs/AGN_LX_table_446.log &
python AGN_setup_XYZ.py 447 #> AGN_logs/AGN_LX_table_447.log &
python AGN_setup_XYZ.py 448 #> AGN_logs/AGN_LX_table_448.log &
python AGN_setup_XYZ.py 449 #> AGN_logs/AGN_LX_table_449.log &
python AGN_setup_XYZ.py 450 #> AGN_logs/AGN_LX_table_450.log &
python AGN_setup_XYZ.py 451 #> AGN_logs/AGN_LX_table_451.log &
python AGN_setup_XYZ.py 452 #> AGN_logs/AGN_LX_table_452.log &
python AGN_setup_XYZ.py 453 #> AGN_logs/AGN_LX_table_453.log &
python AGN_setup_XYZ.py 454 #> AGN_logs/AGN_LX_table_454.log &
python AGN_setup_XYZ.py 455 #> AGN_logs/AGN_LX_table_455.log &
python AGN_setup_XYZ.py 456 #> AGN_logs/AGN_LX_table_456.log &
python AGN_setup_XYZ.py 457 #> AGN_logs/AGN_LX_table_457.log &
python AGN_setup_XYZ.py 458 #> AGN_logs/AGN_LX_table_458.log &
python AGN_setup_XYZ.py 459 #> AGN_logs/AGN_LX_table_459.log &
python AGN_setup_XYZ.py 460 #> AGN_logs/AGN_LX_table_460.log &
python AGN_setup_XYZ.py 461 #> AGN_logs/AGN_LX_table_461.log &
python AGN_setup_XYZ.py 462 #> AGN_logs/AGN_LX_table_462.log &
python AGN_setup_XYZ.py 463 #> AGN_logs/AGN_LX_table_463.log &
python AGN_setup_XYZ.py 464 #> AGN_logs/AGN_LX_table_464.log &
python AGN_setup_XYZ.py 465 #> AGN_logs/AGN_LX_table_465.log &
python AGN_setup_XYZ.py 466 #> AGN_logs/AGN_LX_table_466.log &
python AGN_setup_XYZ.py 467 #> AGN_logs/AGN_LX_table_467.log &
python AGN_setup_XYZ.py 468 #> AGN_logs/AGN_LX_table_468.log &
python AGN_setup_XYZ.py 469 #> AGN_logs/AGN_LX_table_469.log &
python AGN_setup_XYZ.py 470 #> AGN_logs/AGN_LX_table_470.log &
python AGN_setup_XYZ.py 471 #> AGN_logs/AGN_LX_table_471.log &
python AGN_setup_XYZ.py 472 #> AGN_logs/AGN_LX_table_472.log &
python AGN_setup_XYZ.py 473 #> AGN_logs/AGN_LX_table_473.log &
python AGN_setup_XYZ.py 474 #> AGN_logs/AGN_LX_table_474.log &
python AGN_setup_XYZ.py 475 #> AGN_logs/AGN_LX_table_475.log &
python AGN_setup_XYZ.py 476 #> AGN_logs/AGN_LX_table_476.log &
python AGN_setup_XYZ.py 477 #> AGN_logs/AGN_LX_table_477.log &
python AGN_setup_XYZ.py 478 #> AGN_logs/AGN_LX_table_478.log &
python AGN_setup_XYZ.py 479 #> AGN_logs/AGN_LX_table_479.log &
python AGN_setup_XYZ.py 480 #> AGN_logs/AGN_LX_table_480.log &
python AGN_setup_XYZ.py 481 #> AGN_logs/AGN_LX_table_481.log &
python AGN_setup_XYZ.py 482 #> AGN_logs/AGN_LX_table_482.log &
python AGN_setup_XYZ.py 483 #> AGN_logs/AGN_LX_table_483.log &
python AGN_setup_XYZ.py 484 #> AGN_logs/AGN_LX_table_484.log &
python AGN_setup_XYZ.py 485 #> AGN_logs/AGN_LX_table_485.log &
python AGN_setup_XYZ.py 486 #> AGN_logs/AGN_LX_table_486.log &
python AGN_setup_XYZ.py 487 #> AGN_logs/AGN_LX_table_487.log &
python AGN_setup_XYZ.py 488 #> AGN_logs/AGN_LX_table_488.log &
python AGN_setup_XYZ.py 489 #> AGN_logs/AGN_LX_table_489.log &
python AGN_setup_XYZ.py 490 #> AGN_logs/AGN_LX_table_490.log &
python AGN_setup_XYZ.py 491 #> AGN_logs/AGN_LX_table_491.log &
python AGN_setup_XYZ.py 492 #> AGN_logs/AGN_LX_table_492.log &
python AGN_setup_XYZ.py 493 #> AGN_logs/AGN_LX_table_493.log &
python AGN_setup_XYZ.py 494 #> AGN_logs/AGN_LX_table_494.log &
python AGN_setup_XYZ.py 495 #> AGN_logs/AGN_LX_table_495.log &
python AGN_setup_XYZ.py 496 #> AGN_logs/AGN_LX_table_496.log &
python AGN_setup_XYZ.py 497 #> AGN_logs/AGN_LX_table_497.log &
python AGN_setup_XYZ.py 498 #> AGN_logs/AGN_LX_table_498.log &
python AGN_setup_XYZ.py 499 #> AGN_logs/AGN_LX_table_499.log &
python AGN_setup_XYZ.py 500 #> AGN_logs/AGN_LX_table_500.log &
python AGN_setup_XYZ.py 501 #> AGN_logs/AGN_LX_table_501.log &
python AGN_setup_XYZ.py 502 #> AGN_logs/AGN_LX_table_502.log &
python AGN_setup_XYZ.py 503 #> AGN_logs/AGN_LX_table_503.log &
python AGN_setup_XYZ.py 504 #> AGN_logs/AGN_LX_table_504.log &
python AGN_setup_XYZ.py 505 #> AGN_logs/AGN_LX_table_505.log &
python AGN_setup_XYZ.py 506 #> AGN_logs/AGN_LX_table_506.log &
python AGN_setup_XYZ.py 507 #> AGN_logs/AGN_LX_table_507.log &
python AGN_setup_XYZ.py 508 #> AGN_logs/AGN_LX_table_508.log &
python AGN_setup_XYZ.py 509 #> AGN_logs/AGN_LX_table_509.log &
python AGN_setup_XYZ.py 510 #> AGN_logs/AGN_LX_table_510.log &
python AGN_setup_XYZ.py 511 #> AGN_logs/AGN_LX_table_511.log &
python AGN_setup_XYZ.py 512 #> AGN_logs/AGN_LX_table_512.log &
python AGN_setup_XYZ.py 513 #> AGN_logs/AGN_LX_table_513.log &
python AGN_setup_XYZ.py 514 #> AGN_logs/AGN_LX_table_514.log &
python AGN_setup_XYZ.py 515 #> AGN_logs/AGN_LX_table_515.log &
python AGN_setup_XYZ.py 516 #> AGN_logs/AGN_LX_table_516.log &
python AGN_setup_XYZ.py 517 #> AGN_logs/AGN_LX_table_517.log &
python AGN_setup_XYZ.py 518 #> AGN_logs/AGN_LX_table_518.log &
python AGN_setup_XYZ.py 519 #> AGN_logs/AGN_LX_table_519.log &
python AGN_setup_XYZ.py 520 #> AGN_logs/AGN_LX_table_520.log &
python AGN_setup_XYZ.py 521 #> AGN_logs/AGN_LX_table_521.log &
python AGN_setup_XYZ.py 522 #> AGN_logs/AGN_LX_table_522.log &
python AGN_setup_XYZ.py 523 #> AGN_logs/AGN_LX_table_523.log &
python AGN_setup_XYZ.py 524 #> AGN_logs/AGN_LX_table_524.log &
python AGN_setup_XYZ.py 525 #> AGN_logs/AGN_LX_table_525.log &
python AGN_setup_XYZ.py 526 #> AGN_logs/AGN_LX_table_526.log &
python AGN_setup_XYZ.py 527 #> AGN_logs/AGN_LX_table_527.log &
python AGN_setup_XYZ.py 528 #> AGN_logs/AGN_LX_table_528.log &
python AGN_setup_XYZ.py 529 #> AGN_logs/AGN_LX_table_529.log &
python AGN_setup_XYZ.py 530 #> AGN_logs/AGN_LX_table_530.log &
python AGN_setup_XYZ.py 531 #> AGN_logs/AGN_LX_table_531.log &
python AGN_setup_XYZ.py 532 #> AGN_logs/AGN_LX_table_532.log &
python AGN_setup_XYZ.py 533 #> AGN_logs/AGN_LX_table_533.log &
python AGN_setup_XYZ.py 534 #> AGN_logs/AGN_LX_table_534.log &
python AGN_setup_XYZ.py 535 #> AGN_logs/AGN_LX_table_535.log &
python AGN_setup_XYZ.py 536 #> AGN_logs/AGN_LX_table_536.log &
python AGN_setup_XYZ.py 537 #> AGN_logs/AGN_LX_table_537.log &
python AGN_setup_XYZ.py 538 #> AGN_logs/AGN_LX_table_538.log &
python AGN_setup_XYZ.py 539 #> AGN_logs/AGN_LX_table_539.log &
python AGN_setup_XYZ.py 540 #> AGN_logs/AGN_LX_table_540.log &
python AGN_setup_XYZ.py 541 #> AGN_logs/AGN_LX_table_541.log &
python AGN_setup_XYZ.py 542 #> AGN_logs/AGN_LX_table_542.log &
python AGN_setup_XYZ.py 543 #> AGN_logs/AGN_LX_table_543.log &
python AGN_setup_XYZ.py 544 #> AGN_logs/AGN_LX_table_544.log &
python AGN_setup_XYZ.py 545 #> AGN_logs/AGN_LX_table_545.log &
python AGN_setup_XYZ.py 546 #> AGN_logs/AGN_LX_table_546.log &
python AGN_setup_XYZ.py 547 #> AGN_logs/AGN_LX_table_547.log &
python AGN_setup_XYZ.py 548 #> AGN_logs/AGN_LX_table_548.log &
python AGN_setup_XYZ.py 549 #> AGN_logs/AGN_LX_table_549.log &
python AGN_setup_XYZ.py 550 #> AGN_logs/AGN_LX_table_550.log &
python AGN_setup_XYZ.py 551 #> AGN_logs/AGN_LX_table_551.log &
python AGN_setup_XYZ.py 552 #> AGN_logs/AGN_LX_table_552.log &
python AGN_setup_XYZ.py 553 #> AGN_logs/AGN_LX_table_553.log &
python AGN_setup_XYZ.py 554 #> AGN_logs/AGN_LX_table_554.log &
python AGN_setup_XYZ.py 555 #> AGN_logs/AGN_LX_table_555.log &
python AGN_setup_XYZ.py 556 #> AGN_logs/AGN_LX_table_556.log &
python AGN_setup_XYZ.py 557 #> AGN_logs/AGN_LX_table_557.log &
python AGN_setup_XYZ.py 558 #> AGN_logs/AGN_LX_table_558.log &
python AGN_setup_XYZ.py 559 #> AGN_logs/AGN_LX_table_559.log &
python AGN_setup_XYZ.py 560 #> AGN_logs/AGN_LX_table_560.log &
python AGN_setup_XYZ.py 561 #> AGN_logs/AGN_LX_table_561.log &
python AGN_setup_XYZ.py 562 #> AGN_logs/AGN_LX_table_562.log &
python AGN_setup_XYZ.py 563 #> AGN_logs/AGN_LX_table_563.log &
python AGN_setup_XYZ.py 564 #> AGN_logs/AGN_LX_table_564.log &
python AGN_setup_XYZ.py 565 #> AGN_logs/AGN_LX_table_565.log &
python AGN_setup_XYZ.py 566 #> AGN_logs/AGN_LX_table_566.log &
python AGN_setup_XYZ.py 567 #> AGN_logs/AGN_LX_table_567.log &
python AGN_setup_XYZ.py 568 #> AGN_logs/AGN_LX_table_568.log &
python AGN_setup_XYZ.py 569 #> AGN_logs/AGN_LX_table_569.log &
python AGN_setup_XYZ.py 570 #> AGN_logs/AGN_LX_table_570.log &
python AGN_setup_XYZ.py 571 #> AGN_logs/AGN_LX_table_571.log &
python AGN_setup_XYZ.py 572 #> AGN_logs/AGN_LX_table_572.log &
python AGN_setup_XYZ.py 573 #> AGN_logs/AGN_LX_table_573.log &
python AGN_setup_XYZ.py 574 #> AGN_logs/AGN_LX_table_574.log &
python AGN_setup_XYZ.py 575 #> AGN_logs/AGN_LX_table_575.log &
python AGN_setup_XYZ.py 576 #> AGN_logs/AGN_LX_table_576.log &
python AGN_setup_XYZ.py 577 #> AGN_logs/AGN_LX_table_577.log &
python AGN_setup_XYZ.py 578 #> AGN_logs/AGN_LX_table_578.log &
python AGN_setup_XYZ.py 579 #> AGN_logs/AGN_LX_table_579.log &
python AGN_setup_XYZ.py 580 #> AGN_logs/AGN_LX_table_580.log &
python AGN_setup_XYZ.py 581 #> AGN_logs/AGN_LX_table_581.log &
python AGN_setup_XYZ.py 582 #> AGN_logs/AGN_LX_table_582.log &
python AGN_setup_XYZ.py 583 #> AGN_logs/AGN_LX_table_583.log &
python AGN_setup_XYZ.py 584 #> AGN_logs/AGN_LX_table_584.log &
python AGN_setup_XYZ.py 585 #> AGN_logs/AGN_LX_table_585.log &
python AGN_setup_XYZ.py 586 #> AGN_logs/AGN_LX_table_586.log &
python AGN_setup_XYZ.py 587 #> AGN_logs/AGN_LX_table_587.log &
python AGN_setup_XYZ.py 588 #> AGN_logs/AGN_LX_table_588.log &
python AGN_setup_XYZ.py 589 #> AGN_logs/AGN_LX_table_589.log &
python AGN_setup_XYZ.py 590 #> AGN_logs/AGN_LX_table_590.log &
python AGN_setup_XYZ.py 591 #> AGN_logs/AGN_LX_table_591.log &
python AGN_setup_XYZ.py 592 #> AGN_logs/AGN_LX_table_592.log &
python AGN_setup_XYZ.py 593 #> AGN_logs/AGN_LX_table_593.log &
python AGN_setup_XYZ.py 594 #> AGN_logs/AGN_LX_table_594.log &
python AGN_setup_XYZ.py 595 #> AGN_logs/AGN_LX_table_595.log &
python AGN_setup_XYZ.py 596 #> AGN_logs/AGN_LX_table_596.log &
python AGN_setup_XYZ.py 597 #> AGN_logs/AGN_LX_table_597.log &
python AGN_setup_XYZ.py 598 #> AGN_logs/AGN_LX_table_598.log &
python AGN_setup_XYZ.py 599 #> AGN_logs/AGN_LX_table_599.log &
